// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.4
// Generated from: nitro_type_coverage.native.dart
import Foundation
import Combine
import NitroTypeCoverageCpp

public protocol NitroEncodable {
    func toNative() -> UnsafeMutablePointer<UInt8>?
}

// --- Enums ---
public enum TcStatus: Int64 {
  case ok = 0
  case error = 1
  case pending = 2
}

// --- Structs ---
public struct TcPoint {
  public var x: Double
  public var y: Double
  public var z: Double
}

// C-ABI shadow — layout matches the C typedef TcPoint
fileprivate struct _TcPointC {
  var x: Double
  var y: Double
  var z: Double

  static func fromSwift(_ s: TcPoint) -> _TcPointC {
    return _TcPointC(
      x: s.x,
      y: s.y,
      z: s.z
    )
  }

  func toSwift() -> TcPoint {
    return TcPoint(
      x: x,
      y: y,
      z: z
    )
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension TcPoint {
  public static func fromReader(_ r: NitroRecordReader) -> TcPoint {
    return TcPoint(
      x: r.readDouble(),
      y: r.readDouble(),
      z: r.readDouble(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeDouble(x)
    writer.writeDouble(y)
    writer.writeDouble(z)
  }
}

public struct TcConfig: NitroEncodable {
  public var name: String
  public var count: Int64
  public var enabled: Bool
  public var threshold: Double

  public init(name: String, count: Int64, enabled: Bool, threshold: Double) {
    self.name = name
    self.count = count
    self.enabled = enabled
    self.threshold = threshold
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcConfig {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcConfig {
    return TcConfig(
      name: r.readString(),
      count: r.readInt(),
      enabled: r.readBool(),
      threshold: r.readDouble(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(name)
    writer.writeInt(count)
    writer.writeBool(enabled)
    writer.writeDouble(threshold)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct TcMeta: NitroEncodable {
  public var version: Int64
  public var weight: Double
  public var active: Bool
  public var label: String

  public init(version: Int64, weight: Double, active: Bool, label: String) {
    self.version = version
    self.weight = weight
    self.active = active
    self.label = label
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcMeta {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcMeta {
    return TcMeta(
      version: r.readInt(),
      weight: r.readDouble(),
      active: r.readBool(),
      label: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(version)
    writer.writeDouble(weight)
    writer.writeBool(active)
    writer.writeString(label)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct TcPacket: NitroEncodable {
  public var name: String
  public var sequence: Int64
  public var status: TcStatus
  public var valid: Bool

  public init(name: String, sequence: Int64, status: TcStatus, valid: Bool) {
    self.name = name
    self.sequence = sequence
    self.status = status
    self.valid = valid
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcPacket {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcPacket {
    return TcPacket(
      name: r.readString(),
      sequence: r.readInt(),
      status: TcStatus(rawValue: r.readInt())!,
      valid: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(name)
    writer.writeInt(sequence)
    writer.writeInt(status.rawValue)
    writer.writeBool(valid)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct TcNested: NitroEncodable {
  public var label: String
  public var config: TcConfig
  public var version: Int64

  public init(label: String, config: TcConfig, version: Int64) {
    self.label = label
    self.config = config
    self.version = version
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcNested {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcNested {
    return TcNested(
      label: r.readString(),
      config: TcConfig.fromReader(r),
      version: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    config.writeFields(writer)
    writer.writeInt(version)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct TcNullableWrapper: NitroEncodable {
  public var count: NitroNullableInt
  public var rate: NitroNullableDouble
  public var name: String

  public init(count: NitroNullableInt, rate: NitroNullableDouble, name: String) {
    self.count = count
    self.rate = rate
    self.name = name
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcNullableWrapper {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcNullableWrapper {
    return TcNullableWrapper(
      count: NitroNullableInt.fromReader(r),
      rate: NitroNullableDouble.fromReader(r),
      name: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    count.writeFields(writer)
    rate.writeFields(writer)
    writer.writeString(name)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct TcDataRecord: NitroEncodable {
  public var bytes: Data
  public var values: [Int32]
  public var scores: [Double]
  public var label: String

  public init(bytes: Data, values: [Int32], scores: [Double], label: String) {
    self.bytes = bytes
    self.values = values
    self.scores = scores
    self.label = label
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcDataRecord {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcDataRecord {
    return TcDataRecord(
      bytes: r.readBlob(),
      values: { let d = r.readBlob(); return d.withUnsafeBytes { Array($0.bindMemory(to: Int32.self)) } }(),
      scores: { let d = r.readBlob(); return d.withUnsafeBytes { Array($0.bindMemory(to: Double.self)) } }(),
      label: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBlob(bytes)
    values.withUnsafeBufferPointer { writer.writeBlob(Data(buffer: $0)) }
    scores.withUnsafeBufferPointer { writer.writeBlob(Data(buffer: $0)) }
    writer.writeString(label)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct TcStructHolder: NitroEncodable {
  public var label: String
  public var origin: TcPoint
  public var radius: Double

  public init(label: String, origin: TcPoint, radius: Double) {
    self.label = label
    self.origin = origin
    self.radius = radius
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> TcStructHolder {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> TcStructHolder {
    return TcStructHolder(
      label: r.readString(),
      origin: TcPoint.fromReader(r),
      radius: r.readDouble(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    origin.writeFields(writer)
    writer.writeDouble(radius)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroNullableInt: NitroEncodable {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableInt {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableInt {
    return NitroNullableInt(
      hasValue: r.readBool(),
      value: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Int64? { hasValue ? value : nil }
  public static func fromNullable(_ v: Int64?) -> NitroNullableInt {
    return NitroNullableInt(hasValue: v != nil, value: v ?? 0)
  }
}

public struct NitroNullableDouble: NitroEncodable {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableDouble {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableDouble {
    return NitroNullableDouble(
      hasValue: r.readBool(),
      value: r.readDouble(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Double? { hasValue ? value : nil }
  public static func fromNullable(_ v: Double?) -> NitroNullableDouble {
    return NitroNullableDouble(hasValue: v != nil, value: v ?? 0.0)
  }
}

public struct NitroNullableBool: NitroEncodable {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableBool {
    return NitroNullableBool(
      hasValue: r.readBool(),
      value: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Bool? { hasValue ? value : nil }
  public static func fromNullable(_ v: Bool?) -> NitroNullableBool {
    return NitroNullableBool(hasValue: v != nil, value: v ?? false)
  }
}

public class NitroRecordWriter {
  public var bytes: [UInt8] = []
  public init() {}
  public func writeInt(_ v: Int64) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeInt32(_ v: Int32) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeDouble(_ v: Double) {
      var val = v.bitPattern.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeBool(_ v: Bool) {
      bytes.append(v ? 1 : 0)
  }
  public func writeString(_ v: String) {
      let utf8 = Array(v.utf8)
      writeInt32(Int32(utf8.count))
      bytes.append(contentsOf: utf8)
  }
  public func writeNullTag(_ isNull: Bool) {
      bytes.append(isNull ? 0 : 1)
  }
  public func writeBlob(_ v: Data) {
      writeInt32(Int32(v.count))
      bytes.append(contentsOf: Array(v))
  }
  public func toNative() -> UnsafeMutablePointer<UInt8>? {
      let total = 4 + bytes.count
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
      var length = Int32(bytes.count).littleEndian
      _ = memcpy(ptr, &length, 4)
      if bytes.count > 0 {
          _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
      }
      return ptr
  }
  public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items { writeItem(w, item) }
      return w.toNative()
  }
  /// Encodes a list with a per-item byte-offset table for O(1) random access.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
  public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      var blobs: [[UInt8]] = []
      for item in items {
          let w = NitroRecordWriter()
          writeItem(w, item)
          blobs.append(w.bytes)
      }
      var pos = 4 + 8 * blobs.count
      var offsets: [Int64] = []
      for blob in blobs {
          offsets.append(Int64(pos))
          pos += blob.count
      }
      let w = NitroRecordWriter()
      w.writeInt32(Int32(blobs.count))
      for off in offsets { w.writeInt(off) }
      for blob in blobs { w.bytes.append(contentsOf: blob) }
      return w.toNative()
  }
}

public class NitroRecordReader {
  public let bytes: UnsafeMutablePointer<UInt8>
  public var pos: Int = 0
  public init(ptr: UnsafeMutablePointer<UInt8>) {
      self.bytes = ptr.advanced(by: 4)
  }
  public init(payload: UnsafeMutablePointer<UInt8>) {
      self.bytes = payload
  }
  public func readInt() -> Int64 {
      var v: Int64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Int64(littleEndian: v)
  }
  public func readInt32() -> Int32 {
      var v: Int32 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 4)
      pos += 4
      return Int32(littleEndian: v)
  }
  public func readDouble() -> Double {
      var v: UInt64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Double(bitPattern: UInt64(littleEndian: v))
  }
  public func readBool() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v != 0
  }
  public func readString() -> String {
      let len = Int(readInt32())
      guard len > 0 else { return "" }
      let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
      pos += len
      return s
  }
  public func readNullTag() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v == 0
  }
  public func readBlob() -> Data {
      let len = Int(readInt32())
      let data = Data(bytes: bytes.advanced(by: pos), count: len)
      pos += len
      return data
  }
  public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
      let len = Int(readInt32())
      if (len == 0) { return nil }
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
      ptr.initialize(from: bytes.advanced(by: pos), count: len)
      pos += len
      return ptr
  }
  public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
  /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// The offset table is skipped; items are read sequentially after it.
  public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      r.pos += Int(count) * 8  // skip Int64 offset table
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
}

public enum TcEvent: NitroEncodable {
  case tap(x: Int64, y: Int64)
  case scroll(delta: Double)
  case resize(width: Int64, height: Int64)

  public static func fromReader(_ r: NitroRecordReader) -> TcEvent {
    let tag = r.bytes[r.pos]
    r.pos += 1
    switch tag {
    case 0: return .tap(x: r.readInt(), y: r.readInt())
    case 1: return .scroll(delta: r.readDouble())
    case 2: return .resize(width: r.readInt(), height: r.readInt())
    default: fatalError("Unknown TcEvent tag: \(tag)")
    }
  }

  public func writeFields(to w: NitroRecordWriter) {
    switch self {
    case .tap(let x, let y):
      w.bytes.append(UInt8(0))
      w.writeInt(x)
      w.writeInt(y)
    case .scroll(let delta):
      w.bytes.append(UInt8(1))
      w.writeDouble(delta)
    case .resize(let width, let height):
      w.bytes.append(UInt8(2))
      w.writeInt(width)
      w.writeInt(height)
    }
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(to: writer)
    return writer.toNative()
  }
}

// Binary map encode/decode — [4B payload_len][4B count][entries: [4B kLen][kBytes][1B tag][vBytes]]
// Type tags: 1=int64, 2=float64, 3=bool, 4=string
private func _nitroEncodeMapBinary(_ m: [String: Any]) -> UnsafeMutablePointer<UInt8>? {
    var payload = Data()
    func writeLE32(_ v: Int32) { var lv = v.littleEndian; payload.append(contentsOf: withUnsafeBytes(of: &lv) { Data($0) }) }
    func writeLE64(_ v: Int64) { var lv = v.littleEndian; payload.append(contentsOf: withUnsafeBytes(of: &lv) { Data($0) }) }
    writeLE32(Int32(m.count))
    for (k, v) in m {
        let kb = k.data(using: .utf8)!; writeLE32(Int32(kb.count)); payload.append(kb)
        if let iv = v as? Int64 { payload.append(1); writeLE64(iv) }
        else if let dv = v as? Double { payload.append(2); writeLE64(Int64(bitPattern: dv.bitPattern)) }
        else if let bv = v as? Bool { payload.append(3); payload.append(bv ? 1 : 0) }
        else { let sv = "\(v)".data(using: .utf8)!; payload.append(4); writeLE32(Int32(sv.count)); payload.append(sv) }
    }
    var lenLE = Int32(payload.count).littleEndian
    let total = 4 + payload.count
    guard let buf = malloc(total) else { return nil }
    withUnsafeBytes(of: &lenLE) { memcpy(buf, $0.baseAddress!, 4) }
    payload.withUnsafeBytes { memcpy(buf.advanced(by: 4), $0.baseAddress!, payload.count) }
    return buf.assumingMemoryBound(to: UInt8.self)
}
private func _nitroDecodeMapBinary(_ ptr: UnsafeMutablePointer<UInt8>) -> [String: Any] {
    let payLen = Int(UnsafeRawPointer(ptr).loadUnaligned(as: UInt32.self).littleEndian)
    let data = Data(bytes: ptr.advanced(by: 4), count: payLen)
    var pos = 0
    func readLE32() -> Int { let v = data[pos..<(pos+4)].withUnsafeBytes { Int($0.loadUnaligned(as: UInt32.self).littleEndian) }; pos += 4; return v }
    func readLE64() -> Int64 { let v = data[pos..<(pos+8)].withUnsafeBytes { Int64(bitPattern: $0.loadUnaligned(as: UInt64.self).littleEndian) }; pos += 8; return v }
    let count = readLE32(); var result = [String: Any]()
    for _ in 0..<count {
        let kLen = readLE32(); let k = String(data: data[pos..<(pos+kLen)], encoding: .utf8)!; pos += kLen
        let tag = data[pos]; pos += 1
        switch tag {
        case 1: result[k] = readLE64()
        case 2: result[k] = Double(bitPattern: UInt64(bitPattern: readLE64()))
        case 3: result[k] = data[pos] != 0; pos += 1
        default: let vLen = readLE32(); result[k] = String(data: data[pos..<(pos+vLen)], encoding: .utf8); pos += vLen
        }
    }
    return result
}

private func _nitroCopyTypedDataReturn(_ bytes: UnsafeRawBufferPointer) -> UnsafeMutablePointer<UInt8>? {
    let headerSize = MemoryLayout<Int64>.size
    let byteLength = bytes.count
    guard let raw = malloc(byteLength + headerSize) else { return nil }
    raw.storeBytes(of: Int64(byteLength), as: Int64.self)
    if let base = bytes.baseAddress, byteLength > 0 {
        memcpy(raw.advanced(by: headerSize), base, byteLength)
    }
    return raw.bindMemory(to: UInt8.self, capacity: byteLength + headerSize)
}

private func _nitroCopyTypedDataArrayReturn<T>(_ values: [T]) -> UnsafeMutablePointer<UInt8>? {
    return values.withUnsafeBufferPointer { buffer in
        _nitroCopyTypedDataReturn(UnsafeRawBufferPointer(buffer))
    }
}

private func _nitroMakeZeroCopyTypedDataReturn(_ bytes: UnsafeRawBufferPointer) -> UnsafeMutablePointer<UInt8>? {
    let headerSize = MemoryLayout<Int64>.size * 3
    let byteLength = bytes.count
    guard let raw = malloc(byteLength + headerSize) else { return nil }
    raw.storeBytes(of: Int64(byteLength), as: Int64.self)
    let payload = raw.advanced(by: headerSize)
    raw.advanced(by: MemoryLayout<Int64>.size).storeBytes(of: Int64(Int(bitPattern: payload)), as: Int64.self)
    raw.advanced(by: MemoryLayout<Int64>.size * 2).storeBytes(of: Int64(0), as: Int64.self)
    if let base = bytes.baseAddress, byteLength > 0 {
        memcpy(payload, base, byteLength)
    }
    return raw.bindMemory(to: UInt8.self, capacity: byteLength + headerSize)
}

private func _nitroMakeZeroCopyTypedDataArrayReturn<T>(_ values: [T]) -> UnsafeMutablePointer<UInt8>? {
    return values.withUnsafeBufferPointer { buffer in
        _nitroMakeZeroCopyTypedDataReturn(UnsafeRawBufferPointer(buffer))
    }
}

// MARK: - @NitroResult encoding helpers

private func _nitroWriteResultTag(_ tag: UInt8, _ payload: UnsafeMutablePointer<UInt8>?, _ payloadLen: Int) -> UnsafeMutablePointer<UInt8>? {
    let total = 1 + payloadLen
    guard let buf = UnsafeMutablePointer<UInt8>.allocate(capacity: total) as UnsafeMutablePointer<UInt8>? else { return nil }
    buf[0] = tag
    if payloadLen > 0, let payload = payload {
        buf.advanced(by: 1).initialize(from: payload, count: payloadLen)
    }
    return buf
}

private func _nitroEncodeResultInt64(_ v: Int64) -> UnsafeMutablePointer<UInt8>? {
    let w = NitroRecordWriter()
    w.writeInt(v)
    guard let payload = w.toNative() else { return _nitroWriteResultTag(0, nil, 0) }
    let payloadLen = 4 + Int(payload.pointee)  // 4B prefix + payload bytes
    return _nitroWriteResultTag(0, payload, payloadLen)
}

// Overload for plain Int (non-nullable) convenience
private func _nitroEncodeResultInt64(_ v: Int) -> UnsafeMutablePointer<UInt8>? {
    return _nitroEncodeResultInt64(Int64(v))
}

private func _nitroEncodeResultFloat64(_ v: Double) -> UnsafeMutablePointer<UInt8>? {
    let w = NitroRecordWriter()
    w.writeDouble(v)
    guard let payload = w.toNative() else { return _nitroWriteResultTag(0, nil, 0) }
    let payloadLen = 4 + Int(payload.pointee)
    return _nitroWriteResultTag(0, payload, payloadLen)
}

private func _nitroEncodeResultBool(_ v: Bool) -> UnsafeMutablePointer<UInt8>? {
    let w = NitroRecordWriter()
    w.writeBool(v)
    guard let payload = w.toNative() else { return _nitroWriteResultTag(0, nil, 0) }
    let payloadLen = 4 + Int(payload.pointee)
    return _nitroWriteResultTag(0, payload, payloadLen)
}

private func _nitroEncodeResultString(_ v: String) -> UnsafeMutablePointer<UInt8>? {
    let w = NitroRecordWriter()
    w.writeString(v)
    guard let payload = w.toNative() else { return _nitroWriteResultTag(0, nil, 0) }
    let payloadLen = 4 + Int(payload.pointee)
    return _nitroWriteResultTag(0, payload, payloadLen)
}

// For @HybridRecord / @NitroVariant result types — encode via toNative()/writeFields
private func _nitroEncodeResultRecord<T: NitroEncodable>(_ v: T) -> UnsafeMutablePointer<UInt8>? {
    guard let payload = v.toNative() else { return _nitroWriteResultTag(0, nil, 0) }
    let payloadLen = 4 + Int(payload.pointee)
    return _nitroWriteResultTag(0, payload, payloadLen)
}

private func _nitroEncodeResultError(_ error: Error) -> UnsafeMutablePointer<UInt8>? {
    let msg = error.localizedDescription
    let w = NitroRecordWriter()
    w.writeString(msg)
    guard let payload = w.toNative() else { return _nitroWriteResultTag(1, nil, 0) }
    let payloadLen = 4 + Int(payload.pointee)
    return _nitroWriteResultTag(1, payload, payloadLen)
}

/**
 * Protocol for the NitroTypeCoverage module.
 * Conform to this in your Swift source code.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroTypeCoverageProtocol: AnyObject {
    // source: nitro_type_coverage.native.dart:16
    func echoInt(value: Int64) -> Int64
    // source: nitro_type_coverage.native.dart:17
    func echoDouble(value: Double) -> Double
    // source: nitro_type_coverage.native.dart:18
    func echoBool(value: Bool) -> Bool
    // source: nitro_type_coverage.native.dart:19
    func echoString(value: String) -> String
    // source: nitro_type_coverage.native.dart:22
    func addInts(a: Int64, b: Int64, c: Int64) -> Int64
    // source: nitro_type_coverage.native.dart:23
    func mulDoubles(a: Double, b: Double) -> Double
    // source: nitro_type_coverage.native.dart:24
    func joinStrings(a: String, b: String, separator: String) -> String
    // source: nitro_type_coverage.native.dart:27
    func echoNullableInt(value: Int64?) -> Int64?
    // source: nitro_type_coverage.native.dart:28
    func echoNullableDouble(value: Double?) -> Double?
    // source: nitro_type_coverage.native.dart:29
    func echoNullableBool(value: Bool?) -> Bool?
    // source: nitro_type_coverage.native.dart:30
    func echoNullableString(value: String?) -> String?
    // source: nitro_type_coverage.native.dart:33
    func echoStatus(value: TcStatus) -> TcStatus
    // source: nitro_type_coverage.native.dart:34
    func echoNullableStatus(value: TcStatus?) -> TcStatus?
    // source: nitro_type_coverage.native.dart:37
    func echoPoint(value: TcPoint) -> TcPoint
    // source: nitro_type_coverage.native.dart:40
    func echoConfig(value: TcConfig) -> TcConfig
    // source: nitro_type_coverage.native.dart:44
    func echoBytes(value: Data) -> Data
    // source: nitro_type_coverage.native.dart:47
    func echoFloats(value: [Float]) -> [Float]
    // source: nitro_type_coverage.native.dart:50
    func echoFloat64s(value: [Double]) -> [Double]
    // source: nitro_type_coverage.native.dart:53
    func echoInt32s(value: [Int32]) -> [Int32]
    // source: nitro_type_coverage.native.dart:57
    func echoInt8s(value: Data) -> Data
    // source: nitro_type_coverage.native.dart:60
    func echoInt16s(value: [Int16]) -> [Int16]
    // source: nitro_type_coverage.native.dart:63
    func echoInt64s(value: [Int64]) -> [Int64]
    // source: nitro_type_coverage.native.dart:67
    func echoIntList(value: [Int64]) async throws -> [Int64]
    // source: nitro_type_coverage.native.dart:70
    func echoDoubleList(value: [Double]) async throws -> [Double]
    // source: nitro_type_coverage.native.dart:73
    func echoStringList(value: [String]) async throws -> [String]
    // source: nitro_type_coverage.native.dart:76
    func echoConfigList(values: [TcConfig]) async throws -> [TcConfig]
    // source: nitro_type_coverage.native.dart:80
    func asyncInt(value: Int64) async throws -> Int64
    // source: nitro_type_coverage.native.dart:83
    func asyncDouble(value: Double) async throws -> Double
    // source: nitro_type_coverage.native.dart:86
    func asyncBool(value: Bool) async throws -> Bool
    // source: nitro_type_coverage.native.dart:89
    func asyncString(value: String) async throws -> String
    // source: nitro_type_coverage.native.dart:92
    func asyncConfig(value: TcConfig) async throws -> TcConfig
    // source: nitro_type_coverage.native.dart:96
    func asyncNullableInt(value: Int64?) async throws -> Int64?
    // source: nitro_type_coverage.native.dart:99
    func asyncNullableDouble(value: Double?) async throws -> Double?
    // source: nitro_type_coverage.native.dart:102
    func asyncNullableBool(value: Bool?) async throws -> Bool?
    // source: nitro_type_coverage.native.dart:105
    func asyncNullableString(value: String?) async throws -> String?
    // source: nitro_type_coverage.native.dart:109
    func asyncPoint(value: TcPoint) async throws -> TcPoint
    // source: nitro_type_coverage.native.dart:112
    func asyncNullableStatus(value: TcStatus?) async throws -> TcStatus?
    // source: nitro_type_coverage.native.dart:115
    func asyncMeta(value: TcMeta) async throws -> TcMeta
    // source: nitro_type_coverage.native.dart:118
    func echoMeta(value: TcMeta) -> TcMeta
    // source: nitro_type_coverage.native.dart:121
    func echoNullableIntSafe(value: NitroNullableInt) -> NitroNullableInt
    // source: nitro_type_coverage.native.dart:122
    func echoNullableDoubleSafe(value: NitroNullableDouble) -> NitroNullableDouble
    // source: nitro_type_coverage.native.dart:123
    func echoNullableBoolSafe(value: NitroNullableBool) -> NitroNullableBool
    // source: nitro_type_coverage.native.dart:127
    func echoDataRecord(value: TcDataRecord) -> TcDataRecord
    // source: nitro_type_coverage.native.dart:133
    func echoIntMap(value: Any) -> Any
    // source: nitro_type_coverage.native.dart:134
    func echoStringMap(value: Any) -> Any
    // source: nitro_type_coverage.native.dart:135
    func echoDoubleMap(value: Any) -> Any
    // source: nitro_type_coverage.native.dart:136
    func echoBoolMap(value: Any) -> Any
    // source: nitro_type_coverage.native.dart:142
    func echoPacket(value: TcPacket) -> TcPacket
    // source: nitro_type_coverage.native.dart:146
    func echoNullablePoint(value: TcPoint?) -> TcPoint?
    // source: nitro_type_coverage.native.dart:152
    func configureConfigStream(seed: TcConfig, count: Int64) -> Void
    // source: nitro_type_coverage.native.dart:156
    func echoNullableConfig(value: TcConfig?) -> TcConfig?
    // source: nitro_type_coverage.native.dart:159
    func echoNested(value: TcNested) -> TcNested
    // source: nitro_type_coverage.native.dart:164
    func echoConfigListSync(values: [TcConfig]) async throws -> [TcConfig]
    // source: nitro_type_coverage.native.dart:167
    func echoNullableWrapper(value: TcNullableWrapper) -> TcNullableWrapper
    // source: nitro_type_coverage.native.dart:171
    func onTransformEvent(transformCb: @escaping (Int64) -> Int64) -> Void
    // source: nitro_type_coverage.native.dart:174
    func echoStructHolder(value: TcStructHolder) -> TcStructHolder
    // source: nitro_type_coverage.native.dart:177
    func onStringTransform(stringCb: @escaping (Int64) -> String) -> Void
    // source: nitro_type_coverage.native.dart:178
    func onDoubleTransform(doubleCb: @escaping (Int64) -> Double) -> Void
    // source: nitro_type_coverage.native.dart:183
    func configureBatchStream(from: Int64, count: Int64) -> Void
    // source: nitro_type_coverage.native.dart:187
    func configureBatchDoubleStream(values: [Double]) -> Void
    // source: nitro_type_coverage.native.dart:191
    func configureBatchBoolStream(values: [Bool]) -> Void
    // source: nitro_type_coverage.native.dart:194
    func onBoolTransform(boolCb: @escaping (Int64) -> Bool) -> Void
    // source: nitro_type_coverage.native.dart:195
    func onStatusTransform(statusCb: @escaping (Int64) -> TcStatus) -> Void
    // source: nitro_type_coverage.native.dart:199
    func echoListBool(value: [Bool]) async throws -> [Bool]
    // source: nitro_type_coverage.native.dart:202
    func echoPointList(values: [TcPoint]) async throws -> [TcPoint]
    // source: nitro_type_coverage.native.dart:206
    func nativeAsyncInt(value: Int64) async throws -> Int64
    // source: nitro_type_coverage.native.dart:209
    func nativeAsyncDouble(value: Double) async throws -> Double
    // source: nitro_type_coverage.native.dart:212
    func nativeAsyncBool(value: Bool) async throws -> Bool
    // source: nitro_type_coverage.native.dart:215
    func nativeAsyncString(value: String) async throws -> String
    // source: nitro_type_coverage.native.dart:220
    func configureStringStream(values: [String]) -> Void
    // source: nitro_type_coverage.native.dart:225
    func configureBlockIntStream(from: Int64, count: Int64) -> Void
    // source: nitro_type_coverage.native.dart:228
    func onPointEvent(pointCb: @escaping (TcPoint) -> Void) -> Void
    // source: nitro_type_coverage.native.dart:229
    func onDetailEvent(detailCb: @escaping (Int64, Double) -> Void) -> Void
    // source: nitro_type_coverage.native.dart:232
    func onIntEvent(callback: @escaping (Int64) -> Void) -> Void
    // source: nitro_type_coverage.native.dart:238
    func onBoolEvent(boolCb: @escaping (Bool) -> Void) -> Void
    // source: nitro_type_coverage.native.dart:239
    func onDoubleEvent(doubleCb: @escaping (Double) -> Void) -> Void
    // source: nitro_type_coverage.native.dart:281
    func configureStream(from: Int64, count: Int64) -> Void
    // source: nitro_type_coverage.native.dart:282
    func configureDoubleStream(start: Double, count: Int64) -> Void
    // source: nitro_type_coverage.native.dart:283
    func configureStatusStream(count: Int64) -> Void
    // source: nitro_type_coverage.native.dart:286
    func throwNative(message: String) -> Void
    // source: nitro_type_coverage.native.dart:289
    func throwNativeAsync(message: String) async throws -> Void
    // source: nitro_type_coverage.native.dart:294
    func acquireBuffer(size: Int64) -> UnsafeMutableRawPointer?
    // source: nitro_type_coverage.native.dart:298
    func echoEvent(event: TcEvent) -> TcEvent
    // source: nitro_type_coverage.native.dart:303
    func safeDiv(a: Double, b: Double) throws -> Double
    // source: nitro_type_coverage.native.dart:308
    func validateLabel(label: String) throws -> String
    // source: nitro_type_coverage.native.dart:314
    func asyncAcquireBuffer(size: Int64) async throws -> UnsafeMutableRawPointer?
    // source: nitro_type_coverage.native.dart:318
    func asyncEchoEvent(event: TcEvent) async throws -> TcEvent
    // source: nitro_type_coverage.native.dart:323
    func asyncSafeDiv(a: Double, b: Double) async throws -> Double
    // source: nitro_type_coverage.native.dart:328
    func asyncValidateLabel(label: String) async throws -> String
    var precision: Int64 { get set }
    var tag: String { get set }
    var nullableRate: Double? { get set }
    var enabled: Bool { get set }
    var currentStatus: TcStatus { get set }
    var nullableCounter: Int64? { get set }
    var optionalFlag: Bool? { get set }
    var configStream: AnyPublisher<TcConfig, Never> { get }
    var batchIntStream: AnyPublisher<Int64, Never> { get }
    var batchDoubleStream: AnyPublisher<Double, Never> { get }
    var batchBoolStream: AnyPublisher<Bool, Never> { get }
    var stringStream: AnyPublisher<String, Never> { get }
    var blockIntStream: AnyPublisher<Int64, Never> { get }
    var intStream: AnyPublisher<Int64, Never> { get }
    var pointStream: AnyPublisher<TcPoint, Never> { get }
    var boolStream: AnyPublisher<Bool, Never> { get }
    var doubleStream: AnyPublisher<Double, Never> { get }
    var statusStream: AnyPublisher<TcStatus, Never> { get }
}

public class NitroTypeCoverageRegistry {
    public static var impl: HybridNitroTypeCoverageProtocol?

    public static func register(_ impl: HybridNitroTypeCoverageProtocol) {
        NitroTypeCoverageRegistry.impl = impl
    }

    // Stream: configStream cancellables keyed by dartPort
    public static var _configStreamCancellables = [Int64: AnyCancellable]()

    // Stream: batchIntStream cancellables keyed by dartPort
    public static var _batchIntStreamCancellables = [Int64: AnyCancellable]()
    public static var _batchIntStreamFlushTimers: [Int64: DispatchSourceTimer] = [:]

    // Stream: batchDoubleStream cancellables keyed by dartPort
    public static var _batchDoubleStreamCancellables = [Int64: AnyCancellable]()
    public static var _batchDoubleStreamFlushTimers: [Int64: DispatchSourceTimer] = [:]

    // Stream: batchBoolStream cancellables keyed by dartPort
    public static var _batchBoolStreamCancellables = [Int64: AnyCancellable]()
    public static var _batchBoolStreamFlushTimers: [Int64: DispatchSourceTimer] = [:]

    // Stream: stringStream cancellables keyed by dartPort
    public static var _stringStreamCancellables = [Int64: AnyCancellable]()

    // Stream: blockIntStream cancellables keyed by dartPort
    public static var _blockIntStreamCancellables = [Int64: AnyCancellable]()

    // Stream: intStream cancellables keyed by dartPort
    public static var _intStreamCancellables = [Int64: AnyCancellable]()

    // Stream: pointStream cancellables keyed by dartPort
    public static var _pointStreamCancellables = [Int64: AnyCancellable]()

    // Stream: boolStream cancellables keyed by dartPort
    public static var _boolStreamCancellables = [Int64: AnyCancellable]()

    // Stream: doubleStream cancellables keyed by dartPort
    public static var _doubleStreamCancellables = [Int64: AnyCancellable]()

    // Stream: statusStream cancellables keyed by dartPort
    public static var _statusStreamCancellables = [Int64: AnyCancellable]()
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

// source: nitro_type_coverage.native.dart:16
@_cdecl("_nitro_type_coverage_call_echoInt")
public func _nitro_type_coverage_call_echoInt(_ value: Int64) -> Int64 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0 }
    return impl.echoInt(value: value)
}

// source: nitro_type_coverage.native.dart:17
@_cdecl("_nitro_type_coverage_call_echoDouble")
public func _nitro_type_coverage_call_echoDouble(_ value: Double) -> Double {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0.0 }
    return impl.echoDouble(value: value)
}

// source: nitro_type_coverage.native.dart:18
@_cdecl("_nitro_type_coverage_call_echoBool")
public func _nitro_type_coverage_call_echoBool(_ value: Int8) -> Int8 {
    return Int8((NitroTypeCoverageRegistry.impl?.echoBool(value: value != 0) ?? false) ? 1 : 0)
}

// source: nitro_type_coverage.native.dart:19
@_cdecl("_nitro_type_coverage_call_echoString")
public func _nitro_type_coverage_call_echoString(_ value: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let valueStr = value != nil ? String(cString: value!) : ""
    return strdup(NitroTypeCoverageRegistry.impl?.echoString(value: valueStr) ?? "")
}

// source: nitro_type_coverage.native.dart:22
@_cdecl("_nitro_type_coverage_call_addInts")
public func _nitro_type_coverage_call_addInts(_ a: Int64, _ b: Int64, _ c: Int64) -> Int64 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0 }
    return impl.addInts(a: a, b: b, c: c)
}

// source: nitro_type_coverage.native.dart:23
@_cdecl("_nitro_type_coverage_call_mulDoubles")
public func _nitro_type_coverage_call_mulDoubles(_ a: Double, _ b: Double) -> Double {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0.0 }
    return impl.mulDoubles(a: a, b: b)
}

// source: nitro_type_coverage.native.dart:24
@_cdecl("_nitro_type_coverage_call_joinStrings")
public func _nitro_type_coverage_call_joinStrings(_ a: UnsafePointer<CChar>?, _ b: UnsafePointer<CChar>?, _ separator: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let aStr = a != nil ? String(cString: a!) : ""
    let bStr = b != nil ? String(cString: b!) : ""
    let separatorStr = separator != nil ? String(cString: separator!) : ""
    return strdup(NitroTypeCoverageRegistry.impl?.joinStrings(a: aStr, b: bStr, separator: separatorStr) ?? "")
}

// source: nitro_type_coverage.native.dart:27
@_cdecl("_nitro_type_coverage_call_echoNullableInt")
public func _nitro_type_coverage_call_echoNullableInt(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let _ni_result = impl.echoNullableInt(value: NitroNullableInt.fromNative(value!.assumingMemoryBound(to: UInt8.self)).nullable)
    return NitroNullableInt.fromNullable(_ni_result).toNative()
}

// source: nitro_type_coverage.native.dart:28
@_cdecl("_nitro_type_coverage_call_echoNullableDouble")
public func _nitro_type_coverage_call_echoNullableDouble(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let _nd_result = impl.echoNullableDouble(value: NitroNullableDouble.fromNative(value!.assumingMemoryBound(to: UInt8.self)).nullable)
    return NitroNullableDouble.fromNullable(_nd_result).toNative()
}

// source: nitro_type_coverage.native.dart:29
@_cdecl("_nitro_type_coverage_call_echoNullableBool")
public func _nitro_type_coverage_call_echoNullableBool(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let _nb_result = impl.echoNullableBool(value: NitroNullableBool.fromNative(value!.assumingMemoryBound(to: UInt8.self)).nullable)
    return NitroNullableBool.fromNullable(_nb_result).toNative()
}

// source: nitro_type_coverage.native.dart:30
@_cdecl("_nitro_type_coverage_call_echoNullableString")
public func _nitro_type_coverage_call_echoNullableString(_ value: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let valueStr = value != nil ? String(cString: value!) : ""
    return strdup(NitroTypeCoverageRegistry.impl?.echoNullableString(value: valueStr) ?? "")
}

// source: nitro_type_coverage.native.dart:33
@_cdecl("_nitro_type_coverage_call_echoStatus")
public func _nitro_type_coverage_call_echoStatus(_ value: Int64) -> Int64 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0 }
    return impl.echoStatus(value: TcStatus(rawValue: value)!).rawValue
}

// source: nitro_type_coverage.native.dart:34
@_cdecl("_nitro_type_coverage_call_echoNullableStatus")
public func _nitro_type_coverage_call_echoNullableStatus(_ value: Int64) -> Int64 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return -1 }
    return impl.echoNullableStatus(value: TcStatus(rawValue: value))?.rawValue ?? -1
}

// source: nitro_type_coverage.native.dart:37
@_cdecl("_nitro_type_coverage_call_echoPoint")
public func _nitro_type_coverage_call_echoPoint(_ value: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    guard let result = NitroTypeCoverageRegistry.impl?.echoPoint(value: value!.assumingMemoryBound(to: _TcPointC.self).pointee.toSwift()) else { return nil }
    let ptr = UnsafeMutablePointer<_TcPointC>.allocate(capacity: 1)
    ptr.initialize(to: _TcPointC.fromSwift(result))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_type_coverage.native.dart:40
@_cdecl("_nitro_type_coverage_call_echoConfig")
public func _nitro_type_coverage_call_echoConfig(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoConfig(value: TcConfig.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:44
@_cdecl("_nitro_type_coverage_call_echoBytes")
public func _nitro_type_coverage_call_echoBytes(_ value: UnsafeMutablePointer<UInt8>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Data(bytes: $0, count: Int(value_length)) } ?? Data()
    guard let r = NitroTypeCoverageRegistry.impl?.echoBytes(value: valueArr) else { return nil }
    return r.withUnsafeBytes { _nitroMakeZeroCopyTypedDataReturn($0) }
}

// source: nitro_type_coverage.native.dart:47
@_cdecl("_nitro_type_coverage_call_echoFloats")
public func _nitro_type_coverage_call_echoFloats(_ value: UnsafeMutablePointer<Float>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Array(UnsafeBufferPointer(start: $0, count: Int(value_length))) } ?? []
    guard let r = NitroTypeCoverageRegistry.impl?.echoFloats(value: valueArr) else { return nil }
    return _nitroMakeZeroCopyTypedDataArrayReturn(r)
}

// source: nitro_type_coverage.native.dart:50
@_cdecl("_nitro_type_coverage_call_echoFloat64s")
public func _nitro_type_coverage_call_echoFloat64s(_ value: UnsafeMutablePointer<Double>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Array(UnsafeBufferPointer(start: $0, count: Int(value_length))) } ?? []
    guard let r = NitroTypeCoverageRegistry.impl?.echoFloat64s(value: valueArr) else { return nil }
    return _nitroMakeZeroCopyTypedDataArrayReturn(r)
}

// source: nitro_type_coverage.native.dart:53
@_cdecl("_nitro_type_coverage_call_echoInt32s")
public func _nitro_type_coverage_call_echoInt32s(_ value: UnsafeMutablePointer<Int32>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Array(UnsafeBufferPointer(start: $0, count: Int(value_length))) } ?? []
    guard let r = NitroTypeCoverageRegistry.impl?.echoInt32s(value: valueArr) else { return nil }
    return _nitroMakeZeroCopyTypedDataArrayReturn(r)
}

// source: nitro_type_coverage.native.dart:57
@_cdecl("_nitro_type_coverage_call_echoInt8s")
public func _nitro_type_coverage_call_echoInt8s(_ value: UnsafeMutablePointer<Int8>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Data(bytes: $0, count: Int(value_length)) } ?? Data()
    guard let r = NitroTypeCoverageRegistry.impl?.echoInt8s(value: valueArr) else { return nil }
    return r.withUnsafeBytes { _nitroMakeZeroCopyTypedDataReturn($0) }
}

// source: nitro_type_coverage.native.dart:60
@_cdecl("_nitro_type_coverage_call_echoInt16s")
public func _nitro_type_coverage_call_echoInt16s(_ value: UnsafeMutablePointer<Int16>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Array(UnsafeBufferPointer(start: $0, count: Int(value_length))) } ?? []
    guard let r = NitroTypeCoverageRegistry.impl?.echoInt16s(value: valueArr) else { return nil }
    return _nitroMakeZeroCopyTypedDataArrayReturn(r)
}

// source: nitro_type_coverage.native.dart:63
@_cdecl("_nitro_type_coverage_call_echoInt64s")
public func _nitro_type_coverage_call_echoInt64s(_ value: UnsafeMutablePointer<Int64>?, _ value_length: Int64) -> UnsafeMutablePointer<UInt8>? {
    let valueArr = value.map { Array(UnsafeBufferPointer(start: $0, count: Int(value_length))) } ?? []
    guard let r = NitroTypeCoverageRegistry.impl?.echoInt64s(value: valueArr) else { return nil }
    return _nitroMakeZeroCopyTypedDataArrayReturn(r)
}

// source: nitro_type_coverage.native.dart:67
@_cdecl("_nitro_type_coverage_call_echoIntList")
public func _nitro_type_coverage_call_echoIntList(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuePtr = value?.assumingMemoryBound(to: UInt8.self)
    let valueDecoded = valuePtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readInt() } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [Int64]? = nil
    Task.detached {
        result = try? await impl.echoIntList(value: valueDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeList(r) { w, e in w.writeInt(e) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:70
@_cdecl("_nitro_type_coverage_call_echoDoubleList")
public func _nitro_type_coverage_call_echoDoubleList(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuePtr = value?.assumingMemoryBound(to: UInt8.self)
    let valueDecoded = valuePtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readDouble() } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [Double]? = nil
    Task.detached {
        result = try? await impl.echoDoubleList(value: valueDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeList(r) { w, e in w.writeDouble(e) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:73
@_cdecl("_nitro_type_coverage_call_echoStringList")
public func _nitro_type_coverage_call_echoStringList(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuePtr = value?.assumingMemoryBound(to: UInt8.self)
    let valueDecoded = valuePtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readString() } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [String]? = nil
    Task.detached {
        result = try? await impl.echoStringList(value: valueDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeList(r) { w, e in w.writeString(e) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:76
@_cdecl("_nitro_type_coverage_call_echoConfigList")
public func _nitro_type_coverage_call_echoConfigList(_ values: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuesPtr = values?.assumingMemoryBound(to: UInt8.self)
    let valuesDecoded = valuesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in TcConfig.fromReader(r) } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [TcConfig]? = nil
    Task.detached {
        result = try? await impl.echoConfigList(values: valuesDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeIndexedList(r) { w, e in e.writeFields(w) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:80
@_cdecl("_nitro_type_coverage_call_asyncInt")
public func _nitro_type_coverage_call_asyncInt(_ value: Int64) -> Int64 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Int64? = nil
    Task.detached {
        result = try? await impl.asyncInt(value: value)
        sema.signal()
    }
    sema.wait()
    return result ?? 0
}

// source: nitro_type_coverage.native.dart:83
@_cdecl("_nitro_type_coverage_call_asyncDouble")
public func _nitro_type_coverage_call_asyncDouble(_ value: Double) -> Double {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0.0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Double? = nil
    Task.detached {
        result = try? await impl.asyncDouble(value: value)
        sema.signal()
    }
    sema.wait()
    return result ?? 0.0
}

// source: nitro_type_coverage.native.dart:86
@_cdecl("_nitro_type_coverage_call_asyncBool")
public func _nitro_type_coverage_call_asyncBool(_ value: Int8) -> Int8 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return 0 }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.asyncBool(value: value != 0)
        sema.signal()
    }
    sema.wait()
    return Int8((result ?? false) ? 1 : 0)
}

// source: nitro_type_coverage.native.dart:89
@_cdecl("_nitro_type_coverage_call_asyncString")
public func _nitro_type_coverage_call_asyncString(_ value: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let valueStr = value != nil ? String(cString: value!) : ""
    guard let impl = NitroTypeCoverageRegistry.impl else { return strdup("") }
    let sema = DispatchSemaphore(value: 0)
    var result = ""
    Task.detached {
        result = (try? await impl.asyncString(value: valueStr)) ?? ""
        sema.signal()
    }
    sema.wait()
    return strdup(result)
}

// source: nitro_type_coverage.native.dart:92
@_cdecl("_nitro_type_coverage_call_asyncConfig")
public func _nitro_type_coverage_call_asyncConfig(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: TcConfig? = nil
    Task.detached {
        result = try? await impl.asyncConfig(value: TcConfig.fromNative(value!.assumingMemoryBound(to: UInt8.self)))
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:96
@_cdecl("_nitro_type_coverage_call_asyncNullableInt")
public func _nitro_type_coverage_call_asyncNullableInt(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: Int64? = nil
    Task.detached {
        result = try? await impl.asyncNullableInt(value: NitroNullableInt.fromNative(value!.assumingMemoryBound(to: UInt8.self)).nullable)
        sema.signal()
    }
    sema.wait()
    return NitroNullableInt.fromNullable(result).toNative()
}

// source: nitro_type_coverage.native.dart:99
@_cdecl("_nitro_type_coverage_call_asyncNullableDouble")
public func _nitro_type_coverage_call_asyncNullableDouble(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: Double? = nil
    Task.detached {
        result = try? await impl.asyncNullableDouble(value: NitroNullableDouble.fromNative(value!.assumingMemoryBound(to: UInt8.self)).nullable)
        sema.signal()
    }
    sema.wait()
    return NitroNullableDouble.fromNullable(result).toNative()
}

// source: nitro_type_coverage.native.dart:102
@_cdecl("_nitro_type_coverage_call_asyncNullableBool")
public func _nitro_type_coverage_call_asyncNullableBool(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: Bool? = nil
    Task.detached {
        result = try? await impl.asyncNullableBool(value: NitroNullableBool.fromNative(value!.assumingMemoryBound(to: UInt8.self)).nullable)
        sema.signal()
    }
    sema.wait()
    return NitroNullableBool.fromNullable(result).toNative()
}

// source: nitro_type_coverage.native.dart:105
@_cdecl("_nitro_type_coverage_call_asyncNullableString")
public func _nitro_type_coverage_call_asyncNullableString(_ value: UnsafePointer<CChar>?) -> UnsafeMutablePointer<CChar>? {
    let valueStr = value != nil ? String(cString: value!) : ""
    guard let impl = NitroTypeCoverageRegistry.impl else { return strdup("") }
    let sema = DispatchSemaphore(value: 0)
    var result = ""
    Task.detached {
        result = (try? await impl.asyncNullableString(value: valueStr)) ?? ""
        sema.signal()
    }
    sema.wait()
    return strdup(result)
}

// source: nitro_type_coverage.native.dart:109
@_cdecl("_nitro_type_coverage_call_asyncPoint")
public func _nitro_type_coverage_call_asyncPoint(_ value: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: TcPoint? = nil
    Task.detached {
        result = try? await impl.asyncPoint(value: value!.assumingMemoryBound(to: _TcPointC.self).pointee.toSwift())
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    let ptr = UnsafeMutablePointer<_TcPointC>.allocate(capacity: 1)
    ptr.initialize(to: _TcPointC.fromSwift(r))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_type_coverage.native.dart:112
@_cdecl("_nitro_type_coverage_call_asyncNullableStatus")
public func _nitro_type_coverage_call_asyncNullableStatus(_ value: Int64) -> Int64 {
    guard let impl = NitroTypeCoverageRegistry.impl else { return -1 }
    let sema = DispatchSemaphore(value: 0)
    var result: TcStatus? = nil
    Task.detached {
        result = try? await impl.asyncNullableStatus(value: TcStatus(rawValue: value))
        sema.signal()
    }
    sema.wait()
    return result?.rawValue ?? -1
}

// source: nitro_type_coverage.native.dart:115
@_cdecl("_nitro_type_coverage_call_asyncMeta")
public func _nitro_type_coverage_call_asyncMeta(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: TcMeta? = nil
    Task.detached {
        result = try? await impl.asyncMeta(value: TcMeta.fromNative(value!.assumingMemoryBound(to: UInt8.self)))
        sema.signal()
    }
    sema.wait()
    return result?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:118
@_cdecl("_nitro_type_coverage_call_echoMeta")
public func _nitro_type_coverage_call_echoMeta(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoMeta(value: TcMeta.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:121
@_cdecl("_nitro_type_coverage_call_echoNullableIntSafe")
public func _nitro_type_coverage_call_echoNullableIntSafe(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoNullableIntSafe(value: NitroNullableInt.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:122
@_cdecl("_nitro_type_coverage_call_echoNullableDoubleSafe")
public func _nitro_type_coverage_call_echoNullableDoubleSafe(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoNullableDoubleSafe(value: NitroNullableDouble.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:123
@_cdecl("_nitro_type_coverage_call_echoNullableBoolSafe")
public func _nitro_type_coverage_call_echoNullableBoolSafe(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoNullableBoolSafe(value: NitroNullableBool.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:127
@_cdecl("_nitro_type_coverage_call_echoDataRecord")
public func _nitro_type_coverage_call_echoDataRecord(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoDataRecord(value: TcDataRecord.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:133
@_cdecl("_nitro_type_coverage_call_echoIntMap")
public func _nitro_type_coverage_call_echoIntMap(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    guard let _rawPtr = value else { return nil }
    let inputMap = _nitroDecodeMapBinary(_rawPtr.assumingMemoryBound(to: UInt8.self))
    let result = impl.echoIntMap(value: inputMap)
    guard let resultMap = result as? [String: Any] else { return nil }
    return _nitroEncodeMapBinary(resultMap)
}

// source: nitro_type_coverage.native.dart:134
@_cdecl("_nitro_type_coverage_call_echoStringMap")
public func _nitro_type_coverage_call_echoStringMap(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    guard let _rawPtr = value else { return nil }
    let inputMap = _nitroDecodeMapBinary(_rawPtr.assumingMemoryBound(to: UInt8.self))
    let result = impl.echoStringMap(value: inputMap)
    guard let resultMap = result as? [String: Any] else { return nil }
    return _nitroEncodeMapBinary(resultMap)
}

// source: nitro_type_coverage.native.dart:135
@_cdecl("_nitro_type_coverage_call_echoDoubleMap")
public func _nitro_type_coverage_call_echoDoubleMap(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    guard let _rawPtr = value else { return nil }
    let inputMap = _nitroDecodeMapBinary(_rawPtr.assumingMemoryBound(to: UInt8.self))
    let result = impl.echoDoubleMap(value: inputMap)
    guard let resultMap = result as? [String: Any] else { return nil }
    return _nitroEncodeMapBinary(resultMap)
}

// source: nitro_type_coverage.native.dart:136
@_cdecl("_nitro_type_coverage_call_echoBoolMap")
public func _nitro_type_coverage_call_echoBoolMap(_ value: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    guard let _rawPtr = value else { return nil }
    let inputMap = _nitroDecodeMapBinary(_rawPtr.assumingMemoryBound(to: UInt8.self))
    let result = impl.echoBoolMap(value: inputMap)
    guard let resultMap = result as? [String: Any] else { return nil }
    return _nitroEncodeMapBinary(resultMap)
}

// source: nitro_type_coverage.native.dart:142
@_cdecl("_nitro_type_coverage_call_echoPacket")
public func _nitro_type_coverage_call_echoPacket(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoPacket(value: TcPacket.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:146
@_cdecl("_nitro_type_coverage_call_echoNullablePoint")
public func _nitro_type_coverage_call_echoNullablePoint(_ value: UnsafeRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl, let result = impl.echoNullablePoint(value: value.map { $0.assumingMemoryBound(to: _TcPointC.self).pointee.toSwift() }) else { return nil }
    let ptr = UnsafeMutablePointer<_TcPointC>.allocate(capacity: 1)
    ptr.initialize(to: _TcPointC.fromSwift(result))
    return UnsafeMutableRawPointer(ptr)
}

// source: nitro_type_coverage.native.dart:152
@_cdecl("_nitro_type_coverage_call_configureConfigStream")
public func _nitro_type_coverage_call_configureConfigStream(_ seed: UnsafeMutableRawPointer?, _ count: Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.configureConfigStream(seed: TcConfig.fromNative(seed!.assumingMemoryBound(to: UInt8.self)), count: count)
}

// source: nitro_type_coverage.native.dart:156
@_cdecl("_nitro_type_coverage_call_echoNullableConfig")
public func _nitro_type_coverage_call_echoNullableConfig(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoNullableConfig(value: value.map { TcConfig.fromNative($0.assumingMemoryBound(to: UInt8.self)) })?.toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:159
@_cdecl("_nitro_type_coverage_call_echoNested")
public func _nitro_type_coverage_call_echoNested(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoNested(value: TcNested.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:164
@_cdecl("_nitro_type_coverage_call_echoConfigListSync")
public func _nitro_type_coverage_call_echoConfigListSync(_ values: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuesPtr = values?.assumingMemoryBound(to: UInt8.self)
    let valuesDecoded = valuesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in TcConfig.fromReader(r) } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [TcConfig]? = nil
    Task.detached {
        result = try? await impl.echoConfigListSync(values: valuesDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeIndexedList(r) { w, e in e.writeFields(w) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:167
@_cdecl("_nitro_type_coverage_call_echoNullableWrapper")
public func _nitro_type_coverage_call_echoNullableWrapper(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoNullableWrapper(value: TcNullableWrapper.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:171
@_cdecl("_nitro_type_coverage_call_onTransformEvent")
public func _nitro_type_coverage_call_onTransformEvent(_ transformCb: @convention(c) (Int64) -> Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.onTransformEvent(transformCb: { arg0 in transformCb(arg0) })
}

// source: nitro_type_coverage.native.dart:174
@_cdecl("_nitro_type_coverage_call_echoStructHolder")
public func _nitro_type_coverage_call_echoStructHolder(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.echoStructHolder(value: TcStructHolder.fromNative(value!.assumingMemoryBound(to: UInt8.self))).toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:177
@_cdecl("_nitro_type_coverage_call_onStringTransform")
public func _nitro_type_coverage_call_onStringTransform(_ stringCb: @convention(c) (Int64) -> UnsafeMutablePointer<CChar>?) -> Void {
    NitroTypeCoverageRegistry.impl?.onStringTransform(stringCb: { arg0 in { let _cs = stringCb(arg0); let _str = _cs.map { String(cString: $0) } ?? ""; _cs.map { free($0) }; return _str }() })
}

// source: nitro_type_coverage.native.dart:178
@_cdecl("_nitro_type_coverage_call_onDoubleTransform")
public func _nitro_type_coverage_call_onDoubleTransform(_ doubleCb: @convention(c) (Int64) -> Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.onDoubleTransform(doubleCb: { arg0 in Double(bitPattern: UInt64(bitPattern: doubleCb(arg0))) })
}

// source: nitro_type_coverage.native.dart:183
@_cdecl("_nitro_type_coverage_call_configureBatchStream")
public func _nitro_type_coverage_call_configureBatchStream(_ from: Int64, _ count: Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.configureBatchStream(from: from, count: count)
}

// source: nitro_type_coverage.native.dart:187
@_cdecl("_nitro_type_coverage_call_configureBatchDoubleStream")
public func _nitro_type_coverage_call_configureBatchDoubleStream(_ values: UnsafeMutableRawPointer?) -> Void {
    let valuesPtr = values?.assumingMemoryBound(to: UInt8.self)
    let valuesDecoded = valuesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readDouble() } } ?? []
    NitroTypeCoverageRegistry.impl?.configureBatchDoubleStream(values: valuesDecoded)
}

// source: nitro_type_coverage.native.dart:191
@_cdecl("_nitro_type_coverage_call_configureBatchBoolStream")
public func _nitro_type_coverage_call_configureBatchBoolStream(_ values: UnsafeMutableRawPointer?) -> Void {
    let valuesPtr = values?.assumingMemoryBound(to: UInt8.self)
    let valuesDecoded = valuesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readBool() } } ?? []
    NitroTypeCoverageRegistry.impl?.configureBatchBoolStream(values: valuesDecoded)
}

// source: nitro_type_coverage.native.dart:194
@_cdecl("_nitro_type_coverage_call_onBoolTransform")
public func _nitro_type_coverage_call_onBoolTransform(_ boolCb: @convention(c) (Int64) -> Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.onBoolTransform(boolCb: { arg0 in (boolCb(arg0)) != 0 })
}

// source: nitro_type_coverage.native.dart:195
@_cdecl("_nitro_type_coverage_call_onStatusTransform")
public func _nitro_type_coverage_call_onStatusTransform(_ statusCb: @convention(c) (Int64) -> Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.onStatusTransform(statusCb: { arg0 in TcStatus(rawValue: statusCb(arg0))! })
}

// source: nitro_type_coverage.native.dart:199
@_cdecl("_nitro_type_coverage_call_echoListBool")
public func _nitro_type_coverage_call_echoListBool(_ value: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuePtr = value?.assumingMemoryBound(to: UInt8.self)
    let valueDecoded = valuePtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readBool() } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [Bool]? = nil
    Task.detached {
        result = try? await impl.echoListBool(value: valueDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeList(r) { w, e in w.writeBool(e) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:202
@_cdecl("_nitro_type_coverage_call_echoPointList")
public func _nitro_type_coverage_call_echoPointList(_ values: UnsafeMutableRawPointer?) -> UnsafeMutableRawPointer? {
    let valuesPtr = values?.assumingMemoryBound(to: UInt8.self)
    let valuesDecoded = valuesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in TcPoint.fromReader(r) } } ?? []
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var result: [TcPoint]? = nil
    Task.detached {
        result = try? await impl.echoPointList(values: valuesDecoded)
        sema.signal()
    }
    sema.wait()
    guard let r = result else { return nil }
    return NitroRecordWriter.encodeIndexedList(r) { w, e in e.writeFields(w) }.map { UnsafeMutableRawPointer($0) }
}

// source: nitro_type_coverage.native.dart:206
@_cdecl("_nitro_type_coverage_call_nativeAsyncInt")
public func _nitro_type_coverage_call_nativeAsyncInt(_ value: Int64, _ dartPort: Int64) {
    guard let impl = NitroTypeCoverageRegistry.impl else {
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        return
    }
    Task.detached {
        let _result = (try? await impl.nativeAsyncInt(value: value)) ?? 0
        var _obj = Dart_CObject()
        _obj.type = Dart_CObject_kInt64
        _obj.value.as_int64 = Int64(_result)
        Dart_PostCObject_DL(dartPort, &_obj)
    }
}

// source: nitro_type_coverage.native.dart:209
@_cdecl("_nitro_type_coverage_call_nativeAsyncDouble")
public func _nitro_type_coverage_call_nativeAsyncDouble(_ value: Double, _ dartPort: Int64) {
    guard let impl = NitroTypeCoverageRegistry.impl else {
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        return
    }
    Task.detached {
        let _result = (try? await impl.nativeAsyncDouble(value: value)) ?? 0.0
        var _obj = Dart_CObject()
        _obj.type = Dart_CObject_kDouble
        _obj.value.as_double = _result
        Dart_PostCObject_DL(dartPort, &_obj)
    }
}

// source: nitro_type_coverage.native.dart:212
@_cdecl("_nitro_type_coverage_call_nativeAsyncBool")
public func _nitro_type_coverage_call_nativeAsyncBool(_ value: Int8, _ dartPort: Int64) {
    guard let impl = NitroTypeCoverageRegistry.impl else {
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        return
    }
    Task.detached {
        let _result = (try? await impl.nativeAsyncBool(value: value != 0)) ?? false
        var _obj = Dart_CObject()
        _obj.type = Dart_CObject_kBool
        _obj.value.as_bool = _result
        Dart_PostCObject_DL(dartPort, &_obj)
    }
}

// source: nitro_type_coverage.native.dart:215
@_cdecl("_nitro_type_coverage_call_nativeAsyncString")
public func _nitro_type_coverage_call_nativeAsyncString(_ value: UnsafePointer<CChar>?, _ dartPort: Int64) {
    let valueStr = value != nil ? String(cString: value!) : ""
    guard let impl = NitroTypeCoverageRegistry.impl else {
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        return
    }
    Task.detached {
        let _result = (try? await impl.nativeAsyncString(value: valueStr)) ?? ""
        _result.withCString { cStr in
            var _obj = Dart_CObject()
            _obj.type = Dart_CObject_kString
            _obj.value.as_string = cStr
            Dart_PostCObject_DL(dartPort, &_obj)
        }
    }
}

// source: nitro_type_coverage.native.dart:220
@_cdecl("_nitro_type_coverage_call_configureStringStream")
public func _nitro_type_coverage_call_configureStringStream(_ values: UnsafeMutableRawPointer?) -> Void {
    let valuesPtr = values?.assumingMemoryBound(to: UInt8.self)
    let valuesDecoded = valuesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readString() } } ?? []
    NitroTypeCoverageRegistry.impl?.configureStringStream(values: valuesDecoded)
}

// source: nitro_type_coverage.native.dart:225
@_cdecl("_nitro_type_coverage_call_configureBlockIntStream")
public func _nitro_type_coverage_call_configureBlockIntStream(_ from: Int64, _ count: Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.configureBlockIntStream(from: from, count: count)
}

// source: nitro_type_coverage.native.dart:228
@_cdecl("_nitro_type_coverage_call_onPointEvent")
public func _nitro_type_coverage_call_onPointEvent(_ pointCb: @convention(c) (Int64, Int64, Int64) -> Void) -> Void {
    NitroTypeCoverageRegistry.impl?.onPointEvent(pointCb: { arg0 in pointCb(Int64(bitPattern: arg0.x.bitPattern), Int64(bitPattern: arg0.y.bitPattern), Int64(bitPattern: arg0.z.bitPattern)) })
}

// source: nitro_type_coverage.native.dart:229
@_cdecl("_nitro_type_coverage_call_onDetailEvent")
public func _nitro_type_coverage_call_onDetailEvent(_ detailCb: @convention(c) (Int64, Int64) -> Void) -> Void {
    NitroTypeCoverageRegistry.impl?.onDetailEvent(detailCb: { arg0, arg1 in detailCb(arg0, Int64(bitPattern: arg1.bitPattern)) })
}

// source: nitro_type_coverage.native.dart:232
@_cdecl("_nitro_type_coverage_call_onIntEvent")
public func _nitro_type_coverage_call_onIntEvent(_ callback: @convention(c) (Int64) -> Void) -> Void {
    NitroTypeCoverageRegistry.impl?.onIntEvent(callback: { arg0 in callback(arg0) })
}

// source: nitro_type_coverage.native.dart:238
@_cdecl("_nitro_type_coverage_call_onBoolEvent")
public func _nitro_type_coverage_call_onBoolEvent(_ boolCb: @convention(c) (Bool) -> Void) -> Void {
    NitroTypeCoverageRegistry.impl?.onBoolEvent(boolCb: { arg0 in boolCb(arg0) })
}

// source: nitro_type_coverage.native.dart:239
@_cdecl("_nitro_type_coverage_call_onDoubleEvent")
public func _nitro_type_coverage_call_onDoubleEvent(_ doubleCb: @convention(c) (Int64) -> Void) -> Void {
    NitroTypeCoverageRegistry.impl?.onDoubleEvent(doubleCb: { arg0 in doubleCb(Int64(bitPattern: arg0.bitPattern)) })
}

// source: nitro_type_coverage.native.dart:281
@_cdecl("_nitro_type_coverage_call_configureStream")
public func _nitro_type_coverage_call_configureStream(_ from: Int64, _ count: Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.configureStream(from: from, count: count)
}

// source: nitro_type_coverage.native.dart:282
@_cdecl("_nitro_type_coverage_call_configureDoubleStream")
public func _nitro_type_coverage_call_configureDoubleStream(_ start: Double, _ count: Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.configureDoubleStream(start: start, count: count)
}

// source: nitro_type_coverage.native.dart:283
@_cdecl("_nitro_type_coverage_call_configureStatusStream")
public func _nitro_type_coverage_call_configureStatusStream(_ count: Int64) -> Void {
    NitroTypeCoverageRegistry.impl?.configureStatusStream(count: count)
}

// source: nitro_type_coverage.native.dart:286
@_cdecl("_nitro_type_coverage_call_throwNative")
public func _nitro_type_coverage_call_throwNative(_ message: UnsafePointer<CChar>?) -> Void {
    let messageStr = message != nil ? String(cString: message!) : ""
    NitroTypeCoverageRegistry.impl?.throwNative(message: messageStr)
}

// source: nitro_type_coverage.native.dart:289
@_cdecl("_nitro_type_coverage_call_throwNativeAsync")
public func _nitro_type_coverage_call_throwNativeAsync(_ message: UnsafePointer<CChar>?) -> Void {
    let messageStr = message != nil ? String(cString: message!) : ""
    guard let impl = NitroTypeCoverageRegistry.impl else { return }
    let sema = DispatchSemaphore(value: 0)
    var _thrownError: Error? = nil
    Task.detached {
        do { try await impl.throwNativeAsync(message: messageStr) }
        catch { _thrownError = error }
        sema.signal()
    }
    sema.wait()
    if let _e = _thrownError {
        NSException(name: NSExceptionName((_e as NSError).domain),
                    reason: (_e as NSError).localizedDescription,
                    userInfo: nil).raise()
    }
}

// source: nitro_type_coverage.native.dart:294
@_cdecl("_nitro_type_coverage_call_acquireBuffer")
public func _nitro_type_coverage_call_acquireBuffer(_ size: Int64) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    return impl.acquireBuffer(size: size)
}

// source: nitro_type_coverage.native.dart:298
@_cdecl("_nitro_type_coverage_call_echoEvent")
public func _nitro_type_coverage_call_echoEvent(_ event: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let _vResult = impl.echoEvent(event: TcEvent.fromReader(NitroRecordReader(ptr: event!.assumingMemoryBound(to: UInt8.self))))
    let _vw = NitroRecordWriter()
    _vResult.writeFields(to: _vw)
    return _vw.toNative().map { UnsafeMutablePointer($0) }
}

// source: nitro_type_coverage.native.dart:303
@_cdecl("_nitro_type_coverage_call_safeDiv")
public func _nitro_type_coverage_call_safeDiv(_ a: Double, _ b: Double) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    do {
        let result = try impl.safeDiv(a: a, b: b)
        return _nitroEncodeResultFloat64(result)
    } catch {
        return _nitroEncodeResultError(error)
    }
}

// source: nitro_type_coverage.native.dart:308
@_cdecl("_nitro_type_coverage_call_validateLabel")
public func _nitro_type_coverage_call_validateLabel(_ label: UnsafePointer<CChar>?) -> UnsafeMutablePointer<UInt8>? {
    let labelStr = label != nil ? String(cString: label!) : ""
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    do {
        let result = try impl.validateLabel(label: labelStr)
        return _nitroEncodeResultString(result)
    } catch {
        return _nitroEncodeResultError(error)
    }
}

// source: nitro_type_coverage.native.dart:314
@_cdecl("_nitro_type_coverage_call_asyncAcquireBuffer")
public func _nitro_type_coverage_call_asyncAcquireBuffer(_ size: Int64) -> UnsafeMutableRawPointer? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var _ownedPtr: UnsafeMutableRawPointer? = nil
    Task.detached {
        _ownedPtr = try? await impl.asyncAcquireBuffer(size: size)
        sema.signal()
    }
    sema.wait()
    return _ownedPtr
}

// source: nitro_type_coverage.native.dart:318
@_cdecl("_nitro_type_coverage_call_asyncEchoEvent")
public func _nitro_type_coverage_call_asyncEchoEvent(_ event: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var _vResult: TcEvent? = nil
    Task.detached {
        _vResult = try? await impl.asyncEchoEvent(event: TcEvent.fromReader(NitroRecordReader(ptr: event!.assumingMemoryBound(to: UInt8.self))))
        sema.signal()
    }
    sema.wait()
    guard let _vr = _vResult else { return nil }
    let _vw = NitroRecordWriter()
    _vr.writeFields(to: _vw)
    return _vw.toNative().map { UnsafeMutablePointer($0) }
}

// source: nitro_type_coverage.native.dart:323
@_cdecl("_nitro_type_coverage_call_asyncSafeDiv")
public func _nitro_type_coverage_call_asyncSafeDiv(_ a: Double, _ b: Double) -> UnsafeMutablePointer<UInt8>? {
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var _nitroOk: Double? = nil
    var _nitroErr: Error? = nil
    Task.detached {
        do { _nitroOk = try await impl.asyncSafeDiv(a: a, b: b) }
        catch { _nitroErr = error }
        sema.signal()
    }
    sema.wait()
    if let _e = _nitroErr { return _nitroEncodeResultError(_e) }
    guard let _ok = _nitroOk else { return nil }
    return _nitroEncodeResultFloat64(_ok)
}

// source: nitro_type_coverage.native.dart:328
@_cdecl("_nitro_type_coverage_call_asyncValidateLabel")
public func _nitro_type_coverage_call_asyncValidateLabel(_ label: UnsafePointer<CChar>?) -> UnsafeMutablePointer<UInt8>? {
    let labelStr = label != nil ? String(cString: label!) : ""
    guard let impl = NitroTypeCoverageRegistry.impl else { return nil }
    let sema = DispatchSemaphore(value: 0)
    var _nitroOk: String? = nil
    var _nitroErr: Error? = nil
    Task.detached {
        do { _nitroOk = try await impl.asyncValidateLabel(label: labelStr) }
        catch { _nitroErr = error }
        sema.signal()
    }
    sema.wait()
    if let _e = _nitroErr { return _nitroEncodeResultError(_e) }
    guard let _ok = _nitroOk else { return nil }
    return _nitroEncodeResultString(_ok)
}

@_cdecl("_nitro_type_coverage_call_get_precision")
public func _nitro_type_coverage_call_get_precision() -> Int64 {
    return NitroTypeCoverageRegistry.impl?.precision ?? 0
}

@_cdecl("_nitro_type_coverage_call_set_precision")
public func _nitro_type_coverage_call_set_precision(_ value: Int64) {
    NitroTypeCoverageRegistry.impl?.precision = value
}

@_cdecl("_nitro_type_coverage_call_get_tag")
public func _nitro_type_coverage_call_get_tag() -> UnsafeMutablePointer<CChar>? {
    return strdup(NitroTypeCoverageRegistry.impl?.tag ?? "")
}

@_cdecl("_nitro_type_coverage_call_set_tag")
public func _nitro_type_coverage_call_set_tag(_ value: UnsafePointer<CChar>?) {
    NitroTypeCoverageRegistry.impl?.tag = value != nil ? String(cString: value!) : ""
}

@_cdecl("_nitro_type_coverage_call_get_nullableRate")
public func _nitro_type_coverage_call_get_nullableRate() -> UnsafeMutablePointer<UInt8>? {
    return NitroNullableDouble.fromNullable(NitroTypeCoverageRegistry.impl?.nullableRate).toNative()
}

@_cdecl("_nitro_type_coverage_call_set_nullableRate")
public func _nitro_type_coverage_call_set_nullableRate(_ value: UnsafeMutableRawPointer?) {
    if let v = value { NitroTypeCoverageRegistry.impl?.nullableRate = NitroNullableDouble.fromNative(v.assumingMemoryBound(to: UInt8.self)).nullable }
}

@_cdecl("_nitro_type_coverage_call_get_enabled")
public func _nitro_type_coverage_call_get_enabled() -> Int8 {
    return NitroTypeCoverageRegistry.impl?.enabled == true ? 1 : 0
}

@_cdecl("_nitro_type_coverage_call_set_enabled")
public func _nitro_type_coverage_call_set_enabled(_ value: Int8) {
    NitroTypeCoverageRegistry.impl?.enabled = value != 0
}

@_cdecl("_nitro_type_coverage_call_get_currentStatus")
public func _nitro_type_coverage_call_get_currentStatus() -> Int64 {
    return NitroTypeCoverageRegistry.impl?.currentStatus.rawValue ?? 0
}

@_cdecl("_nitro_type_coverage_call_set_currentStatus")
public func _nitro_type_coverage_call_set_currentStatus(_ value: Int64) {
    if let actualValue = TcStatus(rawValue: value) {
        NitroTypeCoverageRegistry.impl?.currentStatus = actualValue
    }
}

@_cdecl("_nitro_type_coverage_call_get_nullableCounter")
public func _nitro_type_coverage_call_get_nullableCounter() -> UnsafeMutablePointer<UInt8>? {
    return NitroNullableInt.fromNullable(NitroTypeCoverageRegistry.impl?.nullableCounter).toNative()
}

@_cdecl("_nitro_type_coverage_call_set_nullableCounter")
public func _nitro_type_coverage_call_set_nullableCounter(_ value: UnsafeMutableRawPointer?) {
    if let v = value { NitroTypeCoverageRegistry.impl?.nullableCounter = NitroNullableInt.fromNative(v.assumingMemoryBound(to: UInt8.self)).nullable }
}

@_cdecl("_nitro_type_coverage_call_get_optionalFlag")
public func _nitro_type_coverage_call_get_optionalFlag() -> UnsafeMutablePointer<UInt8>? {
    return NitroNullableBool.fromNullable(NitroTypeCoverageRegistry.impl?.optionalFlag).toNative()
}

@_cdecl("_nitro_type_coverage_call_set_optionalFlag")
public func _nitro_type_coverage_call_set_optionalFlag(_ value: UnsafeMutableRawPointer?) {
    if let v = value { NitroTypeCoverageRegistry.impl?.optionalFlag = NitroNullableBool.fromNative(v.assumingMemoryBound(to: UInt8.self)).nullable }
}

@_cdecl("_nitro_type_coverage_register_configStream_stream")
public func _nitro_type_coverage_register_configStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<UInt8>?) -> Bool
) {
    NitroTypeCoverageRegistry._configStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.configStream.sink { item in
            let raw = item.toNative()
            if !emitCb(dartPort, raw) {
                if let raw { free(UnsafeMutableRawPointer(raw)) }
                NitroTypeCoverageRegistry._configStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_configStream_stream")
public func _nitro_type_coverage_release_configStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._configStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._configStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_batchIntStream_stream")
public func _nitro_type_coverage_register_batchIntStream_stream(
    _ dartPort: Int64,
    _ emitBatch: @convention(c) (Int64, UnsafeMutablePointer<Int64>?, Int32) -> Bool
) {
    let _lock = NSLock()
    var _buf = [Int64]()
    _buf.reserveCapacity(16)
    func _flush() {
        _lock.lock()
        guard !_buf.isEmpty else { _lock.unlock(); return }
        var arr = _buf; _buf.removeAll(keepingCapacity: true)
        _lock.unlock()
        let count = Int32(arr.count)
        _ = arr.withUnsafeMutableBufferPointer { emitBatch(dartPort, $0.baseAddress, count) }
    }
    let _timer = DispatchSource.makeTimerSource(queue: .global())
    _timer.schedule(deadline: .now() + .milliseconds(10), repeating: .milliseconds(10))
    _timer.setEventHandler { _flush() }
    _timer.resume()
    NitroTypeCoverageRegistry._batchIntStreamFlushTimers[dartPort] = _timer
    NitroTypeCoverageRegistry._batchIntStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.batchIntStream.sink { item in
            _lock.lock()
            _buf.append(item)
            let needsFlush = _buf.count >= 16
            _lock.unlock()
            if needsFlush { _flush() }
        }
}

@_cdecl("_nitro_type_coverage_release_batchIntStream_stream")
public func _nitro_type_coverage_release_batchIntStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._batchIntStreamFlushTimers[dartPort]?.cancel()
    NitroTypeCoverageRegistry._batchIntStreamFlushTimers.removeValue(forKey: dartPort)
    NitroTypeCoverageRegistry._batchIntStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._batchIntStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_batchDoubleStream_stream")
public func _nitro_type_coverage_register_batchDoubleStream_stream(
    _ dartPort: Int64,
    _ emitBatch: @convention(c) (Int64, UnsafeMutablePointer<Int64>?, Int32) -> Bool
) {
    let _lock = NSLock()
    var _buf = [Int64]()
    _buf.reserveCapacity(16)
    func _flush() {
        _lock.lock()
        guard !_buf.isEmpty else { _lock.unlock(); return }
        var arr = _buf; _buf.removeAll(keepingCapacity: true)
        _lock.unlock()
        let count = Int32(arr.count)
        _ = arr.withUnsafeMutableBufferPointer { emitBatch(dartPort, $0.baseAddress, count) }
    }
    let _timer = DispatchSource.makeTimerSource(queue: .global())
    _timer.schedule(deadline: .now() + .milliseconds(10), repeating: .milliseconds(10))
    _timer.setEventHandler { _flush() }
    _timer.resume()
    NitroTypeCoverageRegistry._batchDoubleStreamFlushTimers[dartPort] = _timer
    NitroTypeCoverageRegistry._batchDoubleStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.batchDoubleStream.sink { item in
            _lock.lock()
            _buf.append(Int64(bitPattern: item.bitPattern))
            let needsFlush = _buf.count >= 16
            _lock.unlock()
            if needsFlush { _flush() }
        }
}

@_cdecl("_nitro_type_coverage_release_batchDoubleStream_stream")
public func _nitro_type_coverage_release_batchDoubleStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._batchDoubleStreamFlushTimers[dartPort]?.cancel()
    NitroTypeCoverageRegistry._batchDoubleStreamFlushTimers.removeValue(forKey: dartPort)
    NitroTypeCoverageRegistry._batchDoubleStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._batchDoubleStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_batchBoolStream_stream")
public func _nitro_type_coverage_register_batchBoolStream_stream(
    _ dartPort: Int64,
    _ emitBatch: @convention(c) (Int64, UnsafeMutablePointer<Int64>?, Int32) -> Bool
) {
    let _lock = NSLock()
    var _buf = [Int64]()
    _buf.reserveCapacity(16)
    func _flush() {
        _lock.lock()
        guard !_buf.isEmpty else { _lock.unlock(); return }
        var arr = _buf; _buf.removeAll(keepingCapacity: true)
        _lock.unlock()
        let count = Int32(arr.count)
        _ = arr.withUnsafeMutableBufferPointer { emitBatch(dartPort, $0.baseAddress, count) }
    }
    let _timer = DispatchSource.makeTimerSource(queue: .global())
    _timer.schedule(deadline: .now() + .milliseconds(10), repeating: .milliseconds(10))
    _timer.setEventHandler { _flush() }
    _timer.resume()
    NitroTypeCoverageRegistry._batchBoolStreamFlushTimers[dartPort] = _timer
    NitroTypeCoverageRegistry._batchBoolStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.batchBoolStream.sink { item in
            _lock.lock()
            _buf.append(item ? 1 : 0)
            let needsFlush = _buf.count >= 16
            _lock.unlock()
            if needsFlush { _flush() }
        }
}

@_cdecl("_nitro_type_coverage_release_batchBoolStream_stream")
public func _nitro_type_coverage_release_batchBoolStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._batchBoolStreamFlushTimers[dartPort]?.cancel()
    NitroTypeCoverageRegistry._batchBoolStreamFlushTimers.removeValue(forKey: dartPort)
    NitroTypeCoverageRegistry._batchBoolStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._batchBoolStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_stringStream_stream")
public func _nitro_type_coverage_register_stringStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<Int8>?) -> Bool
) {
    NitroTypeCoverageRegistry._stringStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.stringStream.sink { item in
            item.withCString { ptr in
                if !emitCb(dartPort, UnsafeMutablePointer(mutating: ptr)) {
                    NitroTypeCoverageRegistry._stringStreamCancellables.removeValue(forKey: dartPort)?.cancel()
                }
            }
        }
}

@_cdecl("_nitro_type_coverage_release_stringStream_stream")
public func _nitro_type_coverage_release_stringStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._stringStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._stringStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_blockIntStream_stream")
public func _nitro_type_coverage_register_blockIntStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Int64) -> Bool
) {
    NitroTypeCoverageRegistry._blockIntStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.blockIntStream.sink { item in
            if !emitCb(dartPort, item) {
                NitroTypeCoverageRegistry._blockIntStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_blockIntStream_stream")
public func _nitro_type_coverage_release_blockIntStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._blockIntStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._blockIntStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_intStream_stream")
public func _nitro_type_coverage_register_intStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Int64) -> Bool
) {
    NitroTypeCoverageRegistry._intStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.intStream.sink { item in
            if !emitCb(dartPort, item) {
                NitroTypeCoverageRegistry._intStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_intStream_stream")
public func _nitro_type_coverage_release_intStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._intStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._intStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_pointStream_stream")
public func _nitro_type_coverage_register_pointStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutableRawPointer?) -> Bool
) {
    NitroTypeCoverageRegistry._pointStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.pointStream.sink { item in
            let ptr = UnsafeMutablePointer<_TcPointC>.allocate(capacity: 1)
            ptr.initialize(to: _TcPointC.fromSwift(item))
            if !emitCb(dartPort, UnsafeMutableRawPointer(ptr)) {
                ptr.deinitialize(count: 1)
                ptr.deallocate()
                NitroTypeCoverageRegistry._pointStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_pointStream_stream")
public func _nitro_type_coverage_release_pointStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._pointStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._pointStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_boolStream_stream")
public func _nitro_type_coverage_register_boolStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Int8) -> Bool
) {
    NitroTypeCoverageRegistry._boolStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.boolStream.sink { item in
            if !emitCb(dartPort, Int8(item ? 1 : 0)) {
                NitroTypeCoverageRegistry._boolStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_boolStream_stream")
public func _nitro_type_coverage_release_boolStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._boolStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._boolStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_doubleStream_stream")
public func _nitro_type_coverage_register_doubleStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Double) -> Bool
) {
    NitroTypeCoverageRegistry._doubleStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.doubleStream.sink { item in
            if !emitCb(dartPort, item) {
                NitroTypeCoverageRegistry._doubleStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_doubleStream_stream")
public func _nitro_type_coverage_release_doubleStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._doubleStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._doubleStreamCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_type_coverage_register_statusStream_stream")
public func _nitro_type_coverage_register_statusStream_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Int64) -> Bool
) {
    NitroTypeCoverageRegistry._statusStreamCancellables[dartPort] =
        NitroTypeCoverageRegistry.impl?.statusStream.sink { item in
            if !emitCb(dartPort, item.rawValue) {
                NitroTypeCoverageRegistry._statusStreamCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_type_coverage_release_statusStream_stream")
public func _nitro_type_coverage_release_statusStream_stream(_ dartPort: Int64) {
    NitroTypeCoverageRegistry._statusStreamCancellables[dartPort]?.cancel()
    NitroTypeCoverageRegistry._statusStreamCancellables.removeValue(forKey: dartPort)
}
