// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_type_coverage.native.dart
// spec-sha256: 261ee4a90e63445eae0f5084d9403b35631641fe8cc84de752b5d97e9ce5b91e
/// Platform-conditional factory for [NitroTypeCoverage]:
///
/// ```dart
/// import 'nitro_type_coverage.platform.g.dart';
///
/// await ensureNitroTypeCoverageReady();               // no-op on native
/// final api = createNitroTypeCoverageInstance();
/// ```
library;

export 'generated/native/nitro_type_coverage.ffi.g.dart'
    if (dart.library.js_interop) 'generated/web/nitro_type_coverage.web.bridge.g.dart'
    show
        createNitroTypeCoverageInstance,
        ensureNitroTypeCoverageReady,
        hasNitroTypeCoverageBackgroundHost,
        activeNitroTypeCoverageBackgroundJobs,
        runBgEchoInBackground,
        runBgTransformInBackground,
        runBgVariantInBackground,
        runBgNullableInBackground,
        runBgVoidInBackground,
        runBgThrowsInBackground,
        runBgCallsModuleInBackground,
        runBgSlowInBackground,
        runBgAnyMapInBackground,
        runBgTuplesInBackground,
        runBgTicksInBackground,
        runBgPointsInBackground,
        runBgStreamThrowsInBackground,
        runBgInfiniteInBackground,
        runBgAppendInBackground,
        runBgSlowAppendInBackground,
        runBgFailAppendInBackground,
        runBgPersistInBackground;
