// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.7
// Generated from: nitro_type_coverage.native.dart
// spec-sha256: 5984d3ce8fb5114c735b28390127b086a9078c459e85d37487765a6d2ee98af0
/// Platform-conditional factory for [NitroTypeCoverage]:
///
/// ```dart
/// import 'nitro_type_coverage.platform.g.dart';
///
/// await ensureNitroTypeCoverageReady();               // no-op on native
/// final api = createNitroTypeCoverageInstance();
/// ```
library;

export 'generated/native/nitro_type_coverage.ffi.g.dart'
    if (dart.library.js_interop) 'generated/web/nitro_type_coverage.web.bridge.g.dart'
    show
        createNitroTypeCoverageInstance,
        ensureNitroTypeCoverageReady,
        hasNitroTypeCoverageBackgroundHost,
        activeNitroTypeCoverageBackgroundJobs,
        runBgEchoInBackground,
        runBgTransformInBackground,
        runBgVariantInBackground,
        runBgNullableInBackground,
        runBgVoidInBackground,
        runBgThrowsInBackground,
        runBgCallsModuleInBackground,
        runBgSlowInBackground,
        runBgAnyMapInBackground,
        runBgTuplesInBackground,
        runBgTicksInBackground,
        runBgPointsInBackground,
        runBgStreamThrowsInBackground,
        runBgInfiniteInBackground,
        runBgAppendInBackground,
        runBgSlowAppendInBackground,
        runBgFailAppendInBackground,
        runBgPersistInBackground,
        runBgProgressInBackground,
        runBgHandleFirstByteInBackground,
        runBgKeyedMapsInBackground,
        runBgAnyNativeInBackground,
        runBgTickWithCallbackInBackground,
        runBgRecordCallbackInBackground;
