// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.4
// Generated from: nitro_type_coverage.native.dart
part of 'nitro_type_coverage.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension TcStatusNativeExt on TcStatus {
  int get nativeValue => index + 0;
}

extension TcStatusFromNativeExt on int {
  TcStatus toTcStatus() => TcStatus.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class TcPointFfi extends Struct {
  @Double()
  external double x;
  @Double()
  external double y;
  @Double()
  external double z;
}

extension TcPointFfiExt on TcPointFfi {
  TcPoint toDart() {
    return TcPoint(x: x, y: y, z: z);
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension TcPointExt on TcPoint {
  Pointer<TcPointFfi> toNative(Arena arena) {
    final ptr = arena<TcPointFfi>();
    ptr.ref.x = x;
    ptr.ref.y = y;
    ptr.ref.z = z;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [TcPoint].
/// Extends [TcPoint] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `TcPointProxy <: TcPoint`, a `Stream<TcPointProxy>`
/// satisfies `Stream<TcPoint>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_type_coverage_release_TcPoint'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class TcPointProxy extends TcPoint implements Finalizable {
  final Pointer<TcPointFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_type_coverage_release_TcPoint',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  TcPointProxy(this._native) : super(x: 0.0, y: 0.0, z: 0.0) {
    assert(
      _finalizer != null,
      'TcPointProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  double get x => _native.ref.x;
  @override
  double get y => _native.ref.y;
  @override
  double get z => _native.ref.z;

  /// Eagerly copies all fields to a plain [TcPoint] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  TcPoint toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension TcConfigRecordExt on TcConfig {
  static TcConfig fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static TcConfig fromReader(RecordReader r) => TcConfig(
    name: r.readString(),
    count: r.readInt(),
    enabled: r.readBool(),
    threshold: r.readDouble(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeString(name);
    writer.writeInt(count);
    writer.writeBool(enabled);
    writer.writeDouble(threshold);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

extension TcMetaRecordExt on TcMeta {
  static TcMeta fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static TcMeta fromReader(RecordReader r) => TcMeta(
    version: r.readInt(),
    weight: r.readDouble(),
    active: r.readBool(),
    label: r.readString(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(version);
    writer.writeDouble(weight);
    writer.writeBool(active);
    writer.writeString(label);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter();
    writeFields(writer);
    return writer.toNative(alloc);
  }
}

class _NitroTypeCoverageImpl extends NitroTypeCoverage {
  final DynamicLibrary _dylib;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  final Map<Object, NativeCallable<dynamic>> _nativeCallbackCache = {};
  late final Pointer<NativeFinalizerFunction> _typedDataReturnFinalizer = _dylib
      .lookup<NativeFinalizerFunction>(
        'nitro_type_coverage_release_typed_data_return',
      )
      .cast();

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_type_coverage',
      ios: true,
      android: true,
      macos: true,
      windows: false,
      linux: false,
      web: false,
    );
  }

  _NitroTypeCoverageImpl() : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_type_coverage_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_type_coverage: Dart API DL initialization failed with code $initCode.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_type_coverage',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_type_coverage_nitro_abi_version',
      )(),
    );
    NitroRuntime.checkLinkChecksum(
      'nitro_type_coverage',
      '6fc987bf6fe97992',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_type_coverage_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    TcPointProxy._init(_dylib);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_type_coverage)',
      'initialized in ${initSw.elapsedMicroseconds} µs',
    );
  }

  late final int Function(int, Pointer<NitroErrorFfi>) _echoIntPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_int',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final double Function(double, Pointer<NitroErrorFfi>)
  _echoDoublePtr = _dylib
      .lookup<NativeFunction<Double Function(Double, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_double',
      )
      .asFunction<double Function(double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final int Function(int, Pointer<NitroErrorFfi>) _echoBoolPtr = _dylib
      .lookup<NativeFunction<Int8 Function(Int8, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_bool',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _echoStringPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_string');
  late final int Function(int, int, int, Pointer<NitroErrorFfi>) _addIntsPtr =
      _dylib
          .lookup<
            NativeFunction<
              Int64 Function(Int64, Int64, Int64, Pointer<NitroErrorFfi>)
            >
          >('nitro_type_coverage_add_ints')
          .asFunction<int Function(int, int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final double Function(double, double, Pointer<NitroErrorFfi>)
  _mulDoublesPtr = _dylib
      .lookup<
        NativeFunction<Double Function(Double, Double, Pointer<NitroErrorFfi>)>
      >('nitro_type_coverage_mul_doubles')
      .asFunction<double Function(double, double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final Pointer<Utf8> Function(
    Pointer<Utf8>,
    Pointer<Utf8>,
    Pointer<Utf8>,
    Pointer<NitroErrorFfi>,
  )
  _joinStringsPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(
          Pointer<Utf8>,
          Pointer<Utf8>,
          Pointer<Utf8>,
          Pointer<NitroErrorFfi>,
        ),
        Pointer<Utf8> Function(
          Pointer<Utf8>,
          Pointer<Utf8>,
          Pointer<Utf8>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_type_coverage_join_strings');
  late final int Function(int, Pointer<NitroErrorFfi>)
  _echoNullableIntPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_nullable_int',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final double Function(double, Pointer<NitroErrorFfi>)
  _echoNullableDoublePtr = _dylib
      .lookup<NativeFunction<Double Function(Double, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_nullable_double',
      )
      .asFunction<double Function(double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final int Function(int, Pointer<NitroErrorFfi>) _echoNullableBoolPtr =
      _dylib
          .lookup<NativeFunction<Int8 Function(Int8, Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_echo_nullable_bool',
          )
          .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _echoNullableStringPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_nullable_string');
  late final int Function(int, Pointer<NitroErrorFfi>) _echoStatusPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_status',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(int, Pointer<NitroErrorFfi>)
  _echoNullableStatusPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_echo_nullable_status',
      )
      .asFunction<int Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Void> Function(Pointer<Void>, Pointer<NitroErrorFfi>)
  _echoPointPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Void>, Pointer<NitroErrorFfi>),
        Pointer<Void> Function(Pointer<Void>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_point');
  late final Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _echoConfigPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_config');
  late final Pointer<Uint8> Function(
    Pointer<Uint8>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _echoBytesPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_bytes');
  late final Pointer<Uint8> Function(
    Pointer<Float>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _echoFloatsPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Float>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Float>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_floats');
  late final Pointer<Uint8> Function(
    Pointer<Double>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _echoFloat64sPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Double>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Double>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_float64s');
  late final Pointer<Uint8> Function(
    Pointer<Int32>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _echoInt32sPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Int32>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Int32>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_int32s');
  late final Pointer<Uint8> Function(Pointer<Int8>, int, Pointer<NitroErrorFfi>)
  _echoInt8sPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Int8>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Int8>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_int8s');
  late final Pointer<Uint8> Function(
    Pointer<Int16>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _echoInt16sPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Int16>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Int16>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_int16s');
  late final Pointer<Uint8> Function(
    Pointer<Int64>,
    int,
    Pointer<NitroErrorFfi>,
  )
  _echoInt64sPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Int64>, Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Int64>, int, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_int64s');
  late final Pointer<Uint8> Function(Pointer<Uint8>) _echoIntListPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>)
      >('nitro_type_coverage_echo_int_list');
  late final Pointer<Uint8> Function(Pointer<Uint8>) _echoDoubleListPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>)
      >('nitro_type_coverage_echo_double_list');
  late final Pointer<Uint8> Function(Pointer<Uint8>) _echoStringListPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>)
      >('nitro_type_coverage_echo_string_list');
  late final Pointer<Uint8> Function(Pointer<Uint8>) _echoConfigListPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>)
      >('nitro_type_coverage_echo_config_list');
  late final int Function(int) _asyncIntPtr = _dylib
      .lookupFunction<Int64 Function(Int64), int Function(int)>(
        'nitro_type_coverage_async_int',
      );
  late final double Function(double) _asyncDoublePtr = _dylib
      .lookupFunction<Double Function(Double), double Function(double)>(
        'nitro_type_coverage_async_double',
      );
  late final int Function(int) _asyncBoolPtr = _dylib
      .lookupFunction<Int8 Function(Int8), int Function(int)>(
        'nitro_type_coverage_async_bool',
      );
  late final Pointer<Utf8> Function(Pointer<Utf8>) _asyncStringPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>),
        Pointer<Utf8> Function(Pointer<Utf8>)
      >('nitro_type_coverage_async_string');
  late final Pointer<Uint8> Function(Pointer<Uint8>) _asyncConfigPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>)
      >('nitro_type_coverage_async_config');
  late final int Function(int) _asyncNullableIntPtr = _dylib
      .lookupFunction<Int64 Function(Int64), int Function(int)>(
        'nitro_type_coverage_async_nullable_int',
      );
  late final double Function(double) _asyncNullableDoublePtr = _dylib
      .lookupFunction<Double Function(Double), double Function(double)>(
        'nitro_type_coverage_async_nullable_double',
      );
  late final int Function(int) _asyncNullableBoolPtr = _dylib
      .lookupFunction<Int8 Function(Int8), int Function(int)>(
        'nitro_type_coverage_async_nullable_bool',
      );
  late final Pointer<Utf8> Function(Pointer<Utf8>) _asyncNullableStringPtr =
      _dylib.lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>),
        Pointer<Utf8> Function(Pointer<Utf8>)
      >('nitro_type_coverage_async_nullable_string');
  late final Pointer<Void> Function(Pointer<Void>) _asyncPointPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(Pointer<Void>),
        Pointer<Void> Function(Pointer<Void>)
      >('nitro_type_coverage_async_point');
  late final int Function(int) _asyncNullableStatusPtr = _dylib
      .lookupFunction<Int64 Function(Int64), int Function(int)>(
        'nitro_type_coverage_async_nullable_status',
      );
  late final Pointer<Uint8> Function(Pointer<Uint8>) _asyncMetaPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>),
        Pointer<Uint8> Function(Pointer<Uint8>)
      >('nitro_type_coverage_async_meta');
  late final Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _echoMetaPtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_meta');
  late final Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _echoNullableIntSafePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_nullable_int_safe');
  late final Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _echoNullableDoubleSafePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_nullable_double_safe');
  late final Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
  _echoNullableBoolSafePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<Uint8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_echo_nullable_bool_safe');
  late final void Function(
    Pointer<NativeFunction<Void Function(Int64)>>,
    Pointer<NitroErrorFfi>,
  )
  _onIntEventPtr = _dylib
      .lookupFunction<
        Void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_type_coverage_on_int_event');
  late final void Function(
    Pointer<NativeFunction<Void Function(Int64)>>,
    Pointer<NitroErrorFfi>,
  )
  _onBoolEventPtr = _dylib
      .lookupFunction<
        Void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_type_coverage_on_bool_event');
  late final void Function(
    Pointer<NativeFunction<Void Function(Int64)>>,
    Pointer<NitroErrorFfi>,
  )
  _onDoubleEventPtr = _dylib
      .lookupFunction<
        Void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_type_coverage_on_double_event');
  late final void Function(int, int, Pointer<NitroErrorFfi>)
  _configureStreamPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_type_coverage_configure_stream')
      .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(double, int, Pointer<NitroErrorFfi>)
  _configureDoubleStreamPtr = _dylib
      .lookup<
        NativeFunction<Void Function(Double, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_type_coverage_configure_double_stream')
      .asFunction<void Function(double, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, Pointer<NitroErrorFfi>)
  _configureStatusStreamPtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_configure_status_stream',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
  _throwNativePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_throw_native');
  late final void Function(Pointer<Utf8>) _throwNativeAsyncPtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Utf8>),
        void Function(Pointer<Utf8>)
      >('nitro_type_coverage_throw_native_async');
  late final int Function(Pointer<NitroErrorFfi>) _getPrecisionPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_get_precision',
      )
      .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _setPrecisionPtr =
      _dylib
          .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_set_precision',
          )
          .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Utf8> Function(Pointer<NitroErrorFfi>) _getTagPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Pointer<NitroErrorFfi>),
        Pointer<Utf8> Function(Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_get_tag');
  late final void Function(Pointer<Utf8>, Pointer<NitroErrorFfi>) _setTagPtr =
      _dylib.lookupFunction<
        Void Function(Pointer<Utf8>, Pointer<NitroErrorFfi>),
        void Function(Pointer<Utf8>, Pointer<NitroErrorFfi>)
      >('nitro_type_coverage_set_tag');
  late final double Function(Pointer<NitroErrorFfi>) _getNullableRatePtr =
      _dylib
          .lookup<NativeFunction<Double Function(Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_get_nullable_rate',
          )
          .asFunction<double Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(double, Pointer<NitroErrorFfi>)
  _setNullableRatePtr = _dylib
      .lookup<NativeFunction<Void Function(Double, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_set_nullable_rate',
      )
      .asFunction<void Function(double, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(Pointer<NitroErrorFfi>) _getEnabledPtr = _dylib
      .lookup<NativeFunction<Int8 Function(Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_get_enabled',
      )
      .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _setEnabledPtr = _dylib
      .lookup<NativeFunction<Void Function(Int8, Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_set_enabled',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(Pointer<NitroErrorFfi>) _getCurrentStatusPtr = _dylib
      .lookup<NativeFunction<Int64 Function(Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_get_current_status',
      )
      .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _setCurrentStatusPtr =
      _dylib
          .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_set_current_status',
          )
          .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(Pointer<NitroErrorFfi>) _getNullableCounterPtr =
      _dylib
          .lookup<NativeFunction<Int64 Function(Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_get_nullable_counter',
          )
          .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _setNullableCounterPtr =
      _dylib
          .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_set_nullable_counter',
          )
          .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(Pointer<NitroErrorFfi>) _getOptionalFlagPtr = _dylib
      .lookup<NativeFunction<Int8 Function(Pointer<NitroErrorFfi>)>>(
        'nitro_type_coverage_get_optional_flag',
      )
      .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _setOptionalFlagPtr =
      _dylib
          .lookup<NativeFunction<Void Function(Int8, Pointer<NitroErrorFfi>)>>(
            'nitro_type_coverage_set_optional_flag',
          )
          .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int) _registerIntStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_register_int_stream_stream',
      );
  late final void Function(int) _releaseIntStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_release_int_stream_stream',
      );
  late final void Function(int) _registerPointStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_register_point_stream_stream',
      );
  late final void Function(int) _releasePointStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_release_point_stream_stream',
      );
  late final void Function(int) _registerBoolStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_register_bool_stream_stream',
      );
  late final void Function(int) _releaseBoolStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_release_bool_stream_stream',
      );
  late final void Function(int) _registerDoubleStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_register_double_stream_stream',
      );
  late final void Function(int) _releaseDoubleStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_release_double_stream_stream',
      );
  late final void Function(int) _registerStatusStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_register_status_stream_stream',
      );
  late final void Function(int) _releaseStatusStreamPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_type_coverage_release_status_stream_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_type_coverage_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_type_coverage_clear_error',
      );
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
  _getErrorNativePtr = _dylib.lookup('nitro_type_coverage_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('nitro_type_coverage_clear_error');

  @override
  void dispose() {
    NitroRuntime.logLifecycle('dispose(nitro_type_coverage)', 'disposing');
    for (final callback in _nativeCallbackCache.values) {
      callback.close();
    }
    _nativeCallbackCache.clear();
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_type_coverage)', 'disposed');
  }

  // Native callback handles are cached so native code can retain
  // callback pointers safely until this HybridObject is disposed.
  NativeCallable<Void Function(Int64)> _nativeCallbackOnIntEventCallback(
    void Function(int) callback,
  ) {
    final key = ('onIntEvent.callback', callback);
    return _nativeCallbackCache.putIfAbsent(key, () {
          return NativeCallable<Void Function(Int64)>.listener((int arg0) {
            callback(arg0);
          });
        })
        as NativeCallable<Void Function(Int64)>;
  }

  NativeCallable<Void Function(Int64)> _nativeCallbackOnBoolEventBoolCb(
    void Function(bool) callback,
  ) {
    final key = ('onBoolEvent.boolCb', callback);
    return _nativeCallbackCache.putIfAbsent(key, () {
          return NativeCallable<Void Function(Int64)>.listener((int arg0) {
            callback(arg0 != 0);
          });
        })
        as NativeCallable<Void Function(Int64)>;
  }

  NativeCallable<Void Function(Int64)> _nativeCallbackOnDoubleEventDoubleCb(
    void Function(double) callback,
  ) {
    final key = ('onDoubleEvent.doubleCb', callback);
    return _nativeCallbackCache.putIfAbsent(key, () {
          return NativeCallable<Void Function(Int64)>.listener((int arg0) {
            callback(Int64List.fromList([arg0]).buffer.asFloat64List()[0]);
          });
        })
        as NativeCallable<Void Function(Int64)>;
  }

  @override
  int echoInt(int value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoIntPtr(value, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'echoInt');
  }

  @override
  double echoDouble(double value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoDoublePtr(value, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'echoDouble');
  }

  @override
  bool echoBool(bool value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoBoolPtr(value ? 1 : 0, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res != 0;
    }, methodName: 'echoBool');
  }

  @override
  String echoString(String value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoStringPtr(
          value.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        return res.toDartStringWithFree();
      }),
      methodName: 'echoString',
    );
  }

  @override
  int addInts(int a, int b, int c) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _addIntsPtr(a, b, c, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'addInts');
  }

  @override
  double mulDoubles(double a, double b) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _mulDoublesPtr(a, b, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'mulDoubles');
  }

  @override
  String joinStrings(String a, String b, String separator) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _joinStringsPtr(
          a.toNativeUtf8(allocator: arena),
          b.toNativeUtf8(allocator: arena),
          separator.toNativeUtf8(allocator: arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        return res.toDartStringWithFree();
      }),
      methodName: 'joinStrings',
    );
  }

  @override
  int? echoNullableInt(int? value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoNullableIntPtr(value ?? -9223372036854775808, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res == -9223372036854775808 ? null : res;
    }, methodName: 'echoNullableInt');
  }

  @override
  double? echoNullableDouble(double? value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoNullableDoublePtr(value ?? double.nan, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.isNaN ? null : res;
    }, methodName: 'echoNullableDouble');
  }

  @override
  bool? echoNullableBool(bool? value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoNullableBoolPtr(
        value == null ? -1 : (value ? 1 : 0),
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res == -1 ? null : res != 0;
    }, methodName: 'echoNullableBool');
  }

  @override
  String? echoNullableString(String? value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoNullableStringPtr(
          value != null ? value.toNativeUtf8(allocator: arena) : nullptr,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        return res == nullptr ? null : res.toDartStringWithFree();
      }),
      methodName: 'echoNullableString',
    );
  }

  @override
  TcStatus echoStatus(TcStatus value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoStatusPtr(value.nativeValue, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.toTcStatus();
    }, methodName: 'echoStatus');
  }

  @override
  TcStatus? echoNullableStatus(TcStatus? value) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _echoNullableStatusPtr(
        value == null ? -1 : value.nativeValue,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res == -1 ? null : res.toTcStatus();
    }, methodName: 'echoNullableStatus');
  }

  @override
  TcPoint echoPoint(TcPoint value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoPointPtr(
          value.toNative(arena).cast<Void>(),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('echoPoint returned null');
        }
        final structPtr = Pointer<TcPointFfi>.fromAddress(res.address);
        final TcPoint decoded;
        try {
          decoded = structPtr.ref.toDart();
        } finally {
          structPtr.ref.freeFields();
          malloc.free(structPtr);
        }
        return decoded;
      }),
      methodName: 'echoPoint',
    );
  }

  @override
  TcConfig echoConfig(TcConfig value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoConfigPtr(value.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr);
        final TcConfig decoded;
        try {
          decoded = TcConfigRecordExt.fromNative(res);
        } finally {
          malloc.free(res);
        }
        return decoded;
      }),
      methodName: 'echoConfig',
    );
  }

  @override
  Uint8List echoBytes(Uint8List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoBytesPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Uint8List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Uint8>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoBytes',
    );
  }

  @override
  Float32List echoFloats(Float32List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoFloatsPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Float32List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Float>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength ~/ 4,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoFloats',
    );
  }

  @override
  Float64List echoFloat64s(Float64List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoFloat64sPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Float64List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Double>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength ~/ 8,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoFloat64s',
    );
  }

  @override
  Int32List echoInt32s(Int32List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoInt32sPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Int32List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Int32>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength ~/ 4,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoInt32s',
    );
  }

  @override
  Int8List echoInt8s(Int8List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoInt8sPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Int8List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Int8>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoInt8s',
    );
  }

  @override
  Int16List echoInt16s(Int16List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoInt16sPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Int16List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Int16>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength ~/ 2,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoInt16s',
    );
  }

  @override
  Int64List echoInt64s(Int64List value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoInt64sPtr(
          value.toPointer(arena),
          value.length,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        if (res == nullptr) {
          throw StateError('Native Int64List return was null');
        }
        final byteLength = res.cast<Int64>().value;
        final dataAddress = Pointer<Int64>.fromAddress(res.address + 8).value;
        final payloadPtr = Pointer<Int64>.fromAddress(dataAddress);
        return payloadPtr.asTypedList(
          byteLength ~/ 8,
          finalizer: _typedDataReturnFinalizer,
          token: res.cast<Void>(),
        );
      }),
      methodName: 'echoInt64s',
    );
  }

  @override
  Future<List<int>> echoIntList(List<int> value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _echoIntListPtr,
        [
          RecordWriter.encodeIndexedPrimitiveList(
            value,
            (w, e) => w.writeInt(e),
            arena,
          ),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'echoIntList',
      );
      final List<int> decoded;
      try {
        decoded = RecordReader.decodePrimitiveList(rawPtr, (r) => r.readInt());
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<List<double>> echoDoubleList(List<double> value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _echoDoubleListPtr,
        [
          RecordWriter.encodeIndexedPrimitiveList(
            value,
            (w, e) => w.writeDouble(e),
            arena,
          ),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'echoDoubleList',
      );
      final List<double> decoded;
      try {
        decoded = RecordReader.decodePrimitiveList(
          rawPtr,
          (r) => r.readDouble(),
        );
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<List<String>> echoStringList(List<String> value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _echoStringListPtr,
        [
          RecordWriter.encodeIndexedPrimitiveList(
            value,
            (w, e) => w.writeString(e),
            arena,
          ),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'echoStringList',
      );
      final List<String> decoded;
      try {
        decoded = RecordReader.decodePrimitiveList(
          rawPtr,
          (r) => r.readString(),
        );
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<List<TcConfig>> echoConfigList(List<TcConfig> values) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _echoConfigListPtr,
        [
          RecordWriter.encodeIndexedList(
            values,
            (w, e) => e.writeFields(w),
            arena,
          ),
        ],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'echoConfigList',
      );
      return LazyRecordList.decode(
        rawPtr,
        (r) => TcConfigRecordExt.fromReader(r),
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<int> asyncInt(int value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _asyncIntPtr,
      [value],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncInt',
    );
    return res;
  }

  @override
  Future<double> asyncDouble(double value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<double>(
      _asyncDoublePtr,
      [value],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncDouble',
    );
    return res;
  }

  @override
  Future<bool> asyncBool(bool value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _asyncBoolPtr,
      [value ? 1 : 0],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncBool',
    );
    return res != 0;
  }

  @override
  Future<String> asyncString(String value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<Pointer<Utf8>>(
        _asyncStringPtr,
        [value.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'asyncString',
      );
      return res.toDartStringWithFree();
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<TcConfig> asyncConfig(TcConfig value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _asyncConfigPtr,
        [value.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'asyncConfig',
      );
      final TcConfig decoded;
      try {
        decoded = TcConfigRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<int?> asyncNullableInt(int? value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _asyncNullableIntPtr,
      [value ?? -9223372036854775808],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncNullableInt',
    );
    return res == -9223372036854775808 ? null : res;
  }

  @override
  Future<double?> asyncNullableDouble(double? value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<double>(
      _asyncNullableDoublePtr,
      [value ?? double.nan],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncNullableDouble',
    );
    return res.isNaN ? null : res;
  }

  @override
  Future<bool?> asyncNullableBool(bool? value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _asyncNullableBoolPtr,
      [value == null ? -1 : (value ? 1 : 0)],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncNullableBool',
    );
    return res == -1 ? null : res != 0;
  }

  @override
  Future<String?> asyncNullableString(String? value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<Pointer<Utf8>>(
        _asyncNullableStringPtr,
        [value != null ? value.toNativeUtf8(allocator: arena) : nullptr],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'asyncNullableString',
      );
      return res == nullptr ? null : res.toDartStringWithFree();
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<TcPoint> asyncPoint(TcPoint value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Void>>(
        _asyncPointPtr,
        [value.toNative(arena).cast<Void>()],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'asyncPoint',
      );
      if (rawPtr == nullptr) {
        throw StateError('asyncPoint returned null');
      }
      final structPtr = Pointer<TcPointFfi>.fromAddress(rawPtr.address);
      final TcPoint decoded;
      try {
        decoded = structPtr.ref.toDart();
      } finally {
        structPtr.ref.freeFields();
        malloc.free(structPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  Future<TcStatus?> asyncNullableStatus(TcStatus? value) async {
    checkDisposed();
    final res = await NitroRuntime.callAsync<int>(
      _asyncNullableStatusPtr,
      [value == null ? -1 : value.nativeValue],
      getError: _getErrorNativePtr,
      clearError: _clearErrorNativePtr,
      methodName: 'asyncNullableStatus',
    );
    return res == -1 ? null : res.toTcStatus();
  }

  @override
  Future<TcMeta> asyncMeta(TcMeta value) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Uint8>>(
        _asyncMetaPtr,
        [value.toNative(arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'asyncMeta',
      );
      final TcMeta decoded;
      try {
        decoded = TcMetaRecordExt.fromNative(rawPtr);
      } finally {
        malloc.free(rawPtr);
      }
      return decoded;
    } finally {
      arena.releaseAll();
    }
  }

  @override
  TcMeta echoMeta(TcMeta value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoMetaPtr(value.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr);
        final TcMeta decoded;
        try {
          decoded = TcMetaRecordExt.fromNative(res);
        } finally {
          malloc.free(res);
        }
        return decoded;
      }),
      methodName: 'echoMeta',
    );
  }

  @override
  NitroNullableInt echoNullableIntSafe(NitroNullableInt value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoNullableIntSafePtr(value.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr);
        final NitroNullableInt decoded;
        try {
          decoded = NitroNullableInt.fromNative(res);
        } finally {
          malloc.free(res);
        }
        return decoded;
      }),
      methodName: 'echoNullableIntSafe',
    );
  }

  @override
  NitroNullableDouble echoNullableDoubleSafe(NitroNullableDouble value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoNullableDoubleSafePtr(
          value.toNative(arena),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(_nitroErr);
        final NitroNullableDouble decoded;
        try {
          decoded = NitroNullableDouble.fromNative(res);
        } finally {
          malloc.free(res);
        }
        return decoded;
      }),
      methodName: 'echoNullableDoubleSafe',
    );
  }

  @override
  NitroNullableBool echoNullableBoolSafe(NitroNullableBool value) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        final res = _echoNullableBoolSafePtr(value.toNative(arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr);
        final NitroNullableBool decoded;
        try {
          decoded = NitroNullableBool.fromNative(res);
        } finally {
          malloc.free(res);
        }
        return decoded;
      }),
      methodName: 'echoNullableBoolSafe',
    );
  }

  @override
  void onIntEvent(void Function(int) callback) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _onIntEventPtr(
        _nativeCallbackOnIntEventCallback(callback).nativeFunction,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'onIntEvent');
  }

  @override
  void onBoolEvent(void Function(bool) boolCb) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _onBoolEventPtr(
        _nativeCallbackOnBoolEventBoolCb(boolCb).nativeFunction,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'onBoolEvent');
  }

  @override
  void onDoubleEvent(void Function(double) doubleCb) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _onDoubleEventPtr(
        _nativeCallbackOnDoubleEventDoubleCb(doubleCb).nativeFunction,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'onDoubleEvent');
  }

  @override
  void configureStream(int from, int count) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _configureStreamPtr(from, count, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'configureStream');
  }

  @override
  void configureDoubleStream(double start, int count) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _configureDoubleStreamPtr(start, count, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'configureDoubleStream');
  }

  @override
  void configureStatusStream(int count) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _configureStatusStreamPtr(count, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'configureStatusStream');
  }

  @override
  void throwNative(String message) {
    checkDisposed();
    return NitroRuntime.callSync(
      () => withArena((arena) {
        _throwNativePtr(message.toNativeUtf8(allocator: arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr);
        return;
      }),
      methodName: 'throwNative',
    );
  }

  @override
  Future<void> throwNativeAsync(String message) async {
    checkDisposed();
    final arena = Arena();
    try {
      await NitroRuntime.callAsync<void>(
        _throwNativeAsyncPtr,
        [message.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'throwNativeAsync',
      );
    } finally {
      arena.releaseAll();
    }
  }

  @override
  int get precision {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getPrecisionPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res;
    }, methodName: 'get precision');
  }

  @override
  set precision(int value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setPrecisionPtr(value, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'set precision');
  }

  @override
  String get tag {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getTagPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.toDartStringWithFree();
    }, methodName: 'get tag');
  }

  @override
  set tag(String value) {
    checkDisposed();
    NitroRuntime.callSync<void>(
      () => withArena((arena) {
        _setTagPtr(value.toNativeUtf8(allocator: arena), _nitroErr);
        NitroRuntime.throwIfOutParamError(_nitroErr);
      }),
      methodName: 'set tag',
    );
  }

  @override
  double? get nullableRate {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getNullableRatePtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.isNaN ? null : res;
    }, methodName: 'get nullableRate');
  }

  @override
  set nullableRate(double? value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setNullableRatePtr(value ?? double.nan, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'set nullableRate');
  }

  @override
  bool get enabled {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getEnabledPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res != 0;
    }, methodName: 'get enabled');
  }

  @override
  set enabled(bool value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setEnabledPtr(value ? 1 : 0, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'set enabled');
  }

  @override
  TcStatus get currentStatus {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getCurrentStatusPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res.toTcStatus();
    }, methodName: 'get currentStatus');
  }

  @override
  set currentStatus(TcStatus value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setCurrentStatusPtr(value.nativeValue, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'set currentStatus');
  }

  @override
  int? get nullableCounter {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getNullableCounterPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res == -9223372036854775808 ? null : res;
    }, methodName: 'get nullableCounter');
  }

  @override
  set nullableCounter(int? value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setNullableCounterPtr(value ?? -9223372036854775808, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'set nullableCounter');
  }

  @override
  bool? get optionalFlag {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getOptionalFlagPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res == -1 ? null : res != 0;
    }, methodName: 'get optionalFlag');
  }

  @override
  set optionalFlag(bool? value) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setOptionalFlagPtr(value == null ? -1 : (value ? 1 : 0), _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'set optionalFlag');
  }

  @override
  Stream<int> intStream() {
    checkDisposed();
    return NitroRuntime.openStream<int>(
      register: (port) => _registerIntStreamPtr(port),
      unpack: (message) => message as int,
      release: (port) => _releaseIntStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<TcPoint> pointStream() {
    checkDisposed();
    return NitroRuntime.openStream<TcPointProxy>(
      register: (port) => _registerPointStreamPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream pointStream',
          );
        }
        return TcPointProxy(Pointer<TcPointFfi>.fromAddress(message as int));
      },
      release: (port) => _releasePointStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<bool> boolStream() {
    checkDisposed();
    return NitroRuntime.openStream<bool>(
      register: (port) => _registerBoolStreamPtr(port),
      unpack: (message) => (message as int) != 0,
      release: (port) => _releaseBoolStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<double> doubleStream() {
    checkDisposed();
    return NitroRuntime.openStream<double>(
      register: (port) => _registerDoubleStreamPtr(port),
      unpack: (message) => message as double,
      release: (port) => _releaseDoubleStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<TcStatus> statusStream() {
    checkDisposed();
    return NitroRuntime.openStream<TcStatus>(
      register: (port) => _registerStatusStreamPtr(port),
      unpack: (message) => (message as int).toTcStatus(),
      release: (port) => _releaseStatusStreamPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
