// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.1
// Generated from: nitro_type_coverage.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_type_coverage.native.dart';

// Web-split layout (this spec targets web): this part holds only the
// platform-neutral codecs. The dart:ffi implementation lives in
// generated/native/nitro_type_coverage.ffi.g.dart; construct instances via the
// conditional factory in nitro_type_coverage.platform.g.dart.

// --- Enum FFI helpers (generated by Nitrogen) ---

extension TcPriorityNativeExt on TcPriority {
  int get nativeValue {
    switch (this) {
      case TcPriority.low:
        return 0;
      case TcPriority.medium:
        return 100;
      case TcPriority.high:
        return 200;
    }
  }
}

extension TcPriorityFromNativeExt on int {
  TcPriority toTcPriority() {
    switch (this) {
      case 0:
        return TcPriority.low;
      case 100:
        return TcPriority.medium;
      case 200:
        return TcPriority.high;
      default:
        throw ArgumentError('Unknown TcPriority native value: $this');
    }
  }
}

extension TcStatusNativeExt on TcStatus {
  int get nativeValue => index + 0;
}

extension TcStatusFromNativeExt on int {
  TcStatus toTcStatus() => TcStatus.values[this - 0];
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension TcPointRecordExt on TcPoint {
  static TcPoint fromReader(RecordReaderBase r) =>
      TcPoint(x: r.readDouble(), y: r.readDouble(), z: r.readDouble());

  void writeFields(RecordWriterBase writer) {
    writer.writeDouble(x);
    writer.writeDouble(y);
    writer.writeDouble(z);
  }
}

extension TcConfigRecordExt on TcConfig {
  static TcConfig fromReader(RecordReaderBase r) => TcConfig(
    name: r.readString(),
    count: r.readInt(),
    enabled: r.readBool(),
    threshold: r.readDouble(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(name);
    writer.writeInt(count);
    writer.writeBool(enabled);
    writer.writeDouble(threshold);
  }
}

extension TcMetaRecordExt on TcMeta {
  static TcMeta fromReader(RecordReaderBase r) => TcMeta(
    version: r.readInt(),
    weight: r.readDouble(),
    active: r.readBool(),
    label: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(version);
    writer.writeDouble(weight);
    writer.writeBool(active);
    writer.writeString(label);
  }
}

extension TcPacketRecordExt on TcPacket {
  static TcPacket fromReader(RecordReaderBase r) => TcPacket(
    name: r.readString(),
    sequence: r.readInt(),
    status: r.readInt().toTcStatus(),
    valid: r.readBool(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(name);
    writer.writeInt(sequence);
    writer.writeInt(status.nativeValue);
    writer.writeBool(valid);
  }
}

extension TcNestedRecordExt on TcNested {
  static TcNested fromReader(RecordReaderBase r) => TcNested(
    label: r.readString(),
    config: TcConfigRecordExt.fromReader(r),
    version: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(label);
    config.writeFields(writer);
    writer.writeInt(version);
  }
}

extension TcNullableWrapperRecordExt on TcNullableWrapper {
  static TcNullableWrapper fromReader(RecordReaderBase r) => TcNullableWrapper(
    count: NitroNullableInt.fromReader(r),
    rate: NitroNullableDouble.fromReader(r),
    name: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    count.writeFields(writer);
    rate.writeFields(writer);
    writer.writeString(name);
  }
}

extension TcDataRecordRecordExt on TcDataRecord {
  static TcDataRecord fromReader(RecordReaderBase r) => TcDataRecord(
    bytes: r.readBlob(),
    values: Int32List.view(r.readBlob().buffer),
    scores: Float64List.view(r.readBlob().buffer),
    label: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeBlob(bytes);
    writer.writeBlob(
      values.buffer.asUint8List(values.offsetInBytes, values.lengthInBytes),
    );
    writer.writeBlob(
      scores.buffer.asUint8List(scores.offsetInBytes, scores.lengthInBytes),
    );
    writer.writeString(label);
  }
}

extension TcStructHolderRecordExt on TcStructHolder {
  static TcStructHolder fromReader(RecordReaderBase r) => TcStructHolder(
    label: r.readString(),
    origin: TcPointRecordExt.fromReader(r),
    radius: r.readDouble(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(label);
    origin.writeFields(writer);
    writer.writeDouble(radius);
  }
}

extension TcDeepRecordRecordExt on TcDeepRecord {
  static TcDeepRecord fromReader(RecordReaderBase r) => TcDeepRecord(
    label: r.readString(),
    nested: TcNestedRecordExt.fromReader(r),
    depth: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(label);
    nested.writeFields(writer);
    writer.writeInt(depth);
  }
}

// --- @NitroVariant binary extensions (generated by Nitrogen) ---

extension TcEventVariantExt on TcEvent {
  static TcEvent fromReader(RecordReaderBase r) {
    final tag = r.readInt8();
    return switch (tag) {
      0 => TcEventTap(x: r.readInt(), y: r.readInt()),
      1 => TcEventScroll(delta: r.readDouble()),
      2 => TcEventResize(width: r.readInt(), height: r.readInt()),
      3 => TcEventNullable(
        count: r.readBool() ? r.readInt() : null,
        status: r.readBool() ? TcStatus.values[r.readInt().toInt()] : null,
        config: r.readBool() ? TcConfigRecordExt.fromReader(r) : null,
        samples: r.readBool()
            ? List.generate(r.readInt32(), (_) => r.readInt())
            : null,
      ),
      _ => throw ArgumentError('Unknown TcEvent tag: $tag'),
    };
  }

  void writeFields(RecordWriterBase writer) {
    switch (this) {
      case TcEventTap(:final x, :final y):
        writer.writeInt8(0);
        writer.writeInt(x);
        writer.writeInt(y);
      case TcEventScroll(:final delta):
        writer.writeInt8(1);
        writer.writeDouble(delta);
      case TcEventResize(:final width, :final height):
        writer.writeInt8(2);
        writer.writeInt(width);
        writer.writeInt(height);
      case TcEventNullable(
        :final count,
        :final status,
        :final config,
        :final samples,
      ):
        writer.writeInt8(3);
        writer.writeBool(count != null);
        if (count != null) {
          writer.writeInt(count);
        }
        writer.writeBool(status != null);
        if (status != null) {
          writer.writeInt(status.index);
        }
        writer.writeBool(config != null);
        if (config != null) {
          config.writeFields(writer);
        }
        writer.writeBool(samples != null);
        if (samples != null) {
          writer.writeInt32(samples.length);
          for (final e in samples) {
            writer.writeInt(e);
          }
        }
    }
  }
}
