// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_type_coverage.native.dart
// spec-sha256: 0d3516be0f9a1fb0c9134d0620bb58a8c37aec56ea16b93c777b7a1ec509858d
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_type_coverage.native.dart';

// Web-split layout (this spec targets web): this part holds only the
// platform-neutral codecs. The dart:ffi implementation lives in
// generated/native/nitro_type_coverage.ffi.g.dart; construct instances via the
// conditional factory in nitro_type_coverage.platform.g.dart.

// --- Enum FFI helpers (generated by Nitrogen) ---

extension TcPriorityNativeExt on TcPriority {
  int get nativeValue {
    switch (this) {
      case TcPriority.low:
        return 0;
      case TcPriority.medium:
        return 100;
      case TcPriority.high:
        return 200;
    }
  }
}

extension TcPriorityFromNativeExt on int {
  TcPriority toTcPriority() {
    switch (this) {
      case 0:
        return TcPriority.low;
      case 100:
        return TcPriority.medium;
      case 200:
        return TcPriority.high;
      default:
        throw ArgumentError('Unknown TcPriority native value: $this');
    }
  }
}

extension TcStatusNativeExt on TcStatus {
  int get nativeValue => index + 0;
}

extension TcStatusFromNativeExt on int {
  TcStatus toTcStatus() => TcStatus.values[this - 0];
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension TcPointRecordExt on TcPoint {
  static TcPoint fromReader(RecordReaderBase r) =>
      TcPoint(x: r.readDouble(), y: r.readDouble(), z: r.readDouble());

  void writeFields(RecordWriterBase writer) {
    writer.writeDouble(x);
    writer.writeDouble(y);
    writer.writeDouble(z);
  }
}

extension TcConfigRecordExt on TcConfig {
  static TcConfig fromReader(RecordReaderBase r) => TcConfig(
    name: r.readString(),
    count: r.readInt(),
    enabled: r.readBool(),
    threshold: r.readDouble(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(name);
    writer.writeInt(count);
    writer.writeBool(enabled);
    writer.writeDouble(threshold);
  }
}

extension TcMetaRecordExt on TcMeta {
  static TcMeta fromReader(RecordReaderBase r) => TcMeta(
    version: r.readInt(),
    weight: r.readDouble(),
    active: r.readBool(),
    label: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeInt(version);
    writer.writeDouble(weight);
    writer.writeBool(active);
    writer.writeString(label);
  }
}

extension TcPacketRecordExt on TcPacket {
  static TcPacket fromReader(RecordReaderBase r) => TcPacket(
    name: r.readString(),
    sequence: r.readInt(),
    status: r.readInt().toTcStatus(),
    valid: r.readBool(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(name);
    writer.writeInt(sequence);
    writer.writeInt(status.nativeValue);
    writer.writeBool(valid);
  }
}

extension TcNestedRecordExt on TcNested {
  static TcNested fromReader(RecordReaderBase r) => TcNested(
    label: r.readString(),
    config: TcConfigRecordExt.fromReader(r),
    version: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(label);
    config.writeFields(writer);
    writer.writeInt(version);
  }
}

extension TcNullableWrapperRecordExt on TcNullableWrapper {
  static TcNullableWrapper fromReader(RecordReaderBase r) => TcNullableWrapper(
    count: NitroNullableInt.fromReader(r),
    rate: NitroNullableDouble.fromReader(r),
    name: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    count.writeFields(writer);
    rate.writeFields(writer);
    writer.writeString(name);
  }
}

extension TcDataRecordRecordExt on TcDataRecord {
  static TcDataRecord fromReader(RecordReaderBase r) => TcDataRecord(
    bytes: r.readBlob(),
    values: Int32List.view(r.readBlob().buffer),
    scores: Float64List.view(r.readBlob().buffer),
    label: r.readString(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeBlob(bytes);
    writer.writeBlob(
      values.buffer.asUint8List(values.offsetInBytes, values.lengthInBytes),
    );
    writer.writeBlob(
      scores.buffer.asUint8List(scores.offsetInBytes, scores.lengthInBytes),
    );
    writer.writeString(label);
  }
}

extension TcStructHolderRecordExt on TcStructHolder {
  static TcStructHolder fromReader(RecordReaderBase r) => TcStructHolder(
    label: r.readString(),
    origin: TcPointRecordExt.fromReader(r),
    radius: r.readDouble(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(label);
    origin.writeFields(writer);
    writer.writeDouble(radius);
  }
}

extension TcDeepRecordRecordExt on TcDeepRecord {
  static TcDeepRecord fromReader(RecordReaderBase r) => TcDeepRecord(
    label: r.readString(),
    nested: TcNestedRecordExt.fromReader(r),
    depth: r.readInt(),
  );

  void writeFields(RecordWriterBase writer) {
    writer.writeString(label);
    nested.writeFields(writer);
    writer.writeInt(depth);
  }
}

// --- @NitroVariant binary extensions (generated by Nitrogen) ---

extension TcEventVariantExt on TcEvent {
  static TcEvent fromReader(RecordReaderBase r) {
    final tag = r.readInt8();
    return switch (tag) {
      0 => TcEventTap(x: r.readInt(), y: r.readInt()),
      1 => TcEventScroll(delta: r.readDouble()),
      2 => TcEventResize(width: r.readInt(), height: r.readInt()),
      3 => TcEventNullable(
        count: r.readBool() ? r.readInt() : null,
        status: r.readBool() ? TcStatus.values[r.readInt().toInt()] : null,
        config: r.readBool() ? TcConfigRecordExt.fromReader(r) : null,
        samples: r.readBool()
            ? List.generate(r.readInt32(), (_) => r.readInt())
            : null,
      ),
      _ => throw ArgumentError('Unknown TcEvent tag: $tag'),
    };
  }

  void writeFields(RecordWriterBase writer) {
    switch (this) {
      case TcEventTap(:final x, :final y):
        writer.writeInt8(0);
        writer.writeInt(x);
        writer.writeInt(y);
      case TcEventScroll(:final delta):
        writer.writeInt8(1);
        writer.writeDouble(delta);
      case TcEventResize(:final width, :final height):
        writer.writeInt8(2);
        writer.writeInt(width);
        writer.writeInt(height);
      case TcEventNullable(
        :final count,
        :final status,
        :final config,
        :final samples,
      ):
        writer.writeInt8(3);
        writer.writeBool(count != null);
        if (count != null) {
          writer.writeInt(count);
        }
        writer.writeBool(status != null);
        if (status != null) {
          writer.writeInt(status.index);
        }
        writer.writeBool(config != null);
        if (config != null) {
          config.writeFields(writer);
        }
        writer.writeBool(samples != null);
        if (samples != null) {
          writer.writeInt32(samples.length);
          for (final e in samples) {
            writer.writeInt(e);
          }
        }
    }
  }
}

/// Default `throw UnimplementedError` bodies for every member of [NitroTypeCoverage], so
/// hand-written fakes keep compiling when the spec grows:
/// `class FakeNitroTypeCoverage extends NitroTypeCoverage with NitroTypeCoverageDefaults { /* overrides */ }`.
mixin NitroTypeCoverageDefaults on NitroTypeCoverage {
  @override
  int echoInt(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt');
  @override
  double echoDouble(double value) =>
      throw UnimplementedError('NitroTypeCoverage.echoDouble');
  @override
  bool echoBool(bool value) =>
      throw UnimplementedError('NitroTypeCoverage.echoBool');
  @override
  String echoString(String value) =>
      throw UnimplementedError('NitroTypeCoverage.echoString');
  @override
  int addInts(int a, int b, int c) =>
      throw UnimplementedError('NitroTypeCoverage.addInts');
  @override
  double mulDoubles(double a, double b) =>
      throw UnimplementedError('NitroTypeCoverage.mulDoubles');
  @override
  String joinStrings(String a, String b, String separator) =>
      throw UnimplementedError('NitroTypeCoverage.joinStrings');
  @override
  DateTime echoDateTime(DateTime value) =>
      throw UnimplementedError('NitroTypeCoverage.echoDateTime');
  @override
  DateTime? echoNullableDateTime(DateTime? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableDateTime');
  @override
  int? echoNullableInt(int? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableInt');
  @override
  double? echoNullableDouble(double? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableDouble');
  @override
  bool? echoNullableBool(bool? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableBool');
  @override
  String? echoNullableString(String? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableString');
  @override
  TcStatus echoStatus(TcStatus value) =>
      throw UnimplementedError('NitroTypeCoverage.echoStatus');
  @override
  TcStatus? echoNullableStatus(TcStatus? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableStatus');
  @override
  TcPoint echoPoint(TcPoint value) =>
      throw UnimplementedError('NitroTypeCoverage.echoPoint');
  @override
  TcRichStruct echoRichStruct(TcRichStruct value) =>
      throw UnimplementedError('NitroTypeCoverage.echoRichStruct');
  @override
  TcConfig echoConfig(TcConfig value) =>
      throw UnimplementedError('NitroTypeCoverage.echoConfig');
  @override
  Uint8List echoBytes(Uint8List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoBytes');
  @override
  Float32List echoFloats(Float32List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoFloats');
  @override
  Float64List echoFloat64s(Float64List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoFloat64s');
  @override
  Int32List echoInt32s(Int32List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt32s');
  @override
  Int8List echoInt8s(Int8List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt8s');
  @override
  Int16List echoInt16s(Int16List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt16s');
  @override
  Int64List echoInt64s(Int64List value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt64s');
  @override
  Future<List<int>> echoIntList(List<int> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoIntList');
  @override
  Future<List<double>> echoDoubleList(List<double> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoDoubleList');
  @override
  Future<List<String>> echoStringList(List<String> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoStringList');
  @override
  Future<List<TcConfig>> echoConfigList(List<TcConfig> values) =>
      throw UnimplementedError('NitroTypeCoverage.echoConfigList');
  @override
  Future<int> asyncInt(int value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncInt');
  @override
  Future<double> asyncDouble(double value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncDouble');
  @override
  Future<bool> asyncBool(bool value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncBool');
  @override
  Future<String> asyncString(String value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncString');
  @override
  Future<TcConfig> asyncConfig(TcConfig value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncConfig');
  @override
  Future<int?> asyncNullableInt(int? value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncNullableInt');
  @override
  Future<double?> asyncNullableDouble(double? value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncNullableDouble');
  @override
  Future<bool?> asyncNullableBool(bool? value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncNullableBool');
  @override
  Future<String?> asyncNullableString(String? value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncNullableString');
  @override
  Future<TcPoint> asyncPoint(TcPoint value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncPoint');
  @override
  Future<TcStatus?> asyncNullableStatus(TcStatus? value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncNullableStatus');
  @override
  Future<TcMeta> asyncMeta(TcMeta value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncMeta');
  @override
  TcMeta echoMeta(TcMeta value) =>
      throw UnimplementedError('NitroTypeCoverage.echoMeta');
  @override
  NitroNullableInt echoNullableIntSafe(NitroNullableInt value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableIntSafe');
  @override
  NitroNullableDouble echoNullableDoubleSafe(NitroNullableDouble value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableDoubleSafe');
  @override
  NitroNullableBool echoNullableBoolSafe(NitroNullableBool value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableBoolSafe');
  @override
  TcDataRecord echoDataRecord(TcDataRecord value) =>
      throw UnimplementedError('NitroTypeCoverage.echoDataRecord');
  @override
  Map<String, int> echoIntMap(Map<String, int> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoIntMap');
  @override
  Map<String, String> echoStringMap(Map<String, String> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoStringMap');
  @override
  Map<String, double> echoDoubleMap(Map<String, double> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoDoubleMap');
  @override
  Map<String, bool> echoBoolMap(Map<String, bool> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoBoolMap');
  @override
  Map<String, TcConfig> echoConfigMap(Map<String, TcConfig> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoConfigMap');
  @override
  Map<String, TcEvent> echoEventMap(Map<String, TcEvent> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoEventMap');
  @override
  TcOptScalars echoOptScalars(TcOptScalars value) =>
      throw UnimplementedError('NitroTypeCoverage.echoOptScalars');
  @override
  Map<String, int?> echoNullableIntMap(Map<String, int?> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableIntMap');
  @override
  Map<String, double?> echoNullableDoubleMap(Map<String, double?> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableDoubleMap');
  @override
  Map<String, bool?> echoNullableBoolMap(Map<String, bool?> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableBoolMap');
  @override
  Map<String, String?> echoNullableStringMap(Map<String, String?> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableStringMap');
  @override
  TcPacket echoPacket(TcPacket value) =>
      throw UnimplementedError('NitroTypeCoverage.echoPacket');
  @override
  TcPoint? echoNullablePoint(TcPoint? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullablePoint');
  @override
  void configureConfigStream(TcConfig seed, int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureConfigStream');
  @override
  TcConfig? echoNullableConfig(TcConfig? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableConfig');
  @override
  TcNested echoNested(TcNested value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNested');
  @override
  Future<List<TcConfig>> echoConfigListSync(List<TcConfig> values) =>
      throw UnimplementedError('NitroTypeCoverage.echoConfigListSync');
  @override
  TcNullableWrapper echoNullableWrapper(TcNullableWrapper value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableWrapper');
  @override
  void onTransformEvent(int Function(int) transformCb) =>
      throw UnimplementedError('NitroTypeCoverage.onTransformEvent');
  @override
  TcStructHolder echoStructHolder(TcStructHolder value) =>
      throw UnimplementedError('NitroTypeCoverage.echoStructHolder');
  @override
  void onStringTransform(String Function(int) stringCb) =>
      throw UnimplementedError('NitroTypeCoverage.onStringTransform');
  @override
  void onDoubleTransform(double Function(int) doubleCb) =>
      throw UnimplementedError('NitroTypeCoverage.onDoubleTransform');
  @override
  void configureBatchStream(int from, int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureBatchStream');
  @override
  void configureBatchDoubleStream(List<double> values) =>
      throw UnimplementedError('NitroTypeCoverage.configureBatchDoubleStream');
  @override
  void configureBatchBoolStream(List<bool> values) =>
      throw UnimplementedError('NitroTypeCoverage.configureBatchBoolStream');
  @override
  void onBoolTransform(bool Function(int) boolCb) =>
      throw UnimplementedError('NitroTypeCoverage.onBoolTransform');
  @override
  void onStatusTransform(TcStatus Function(int) statusCb) =>
      throw UnimplementedError('NitroTypeCoverage.onStatusTransform');
  @override
  Future<List<bool>> echoListBool(List<bool> value) =>
      throw UnimplementedError('NitroTypeCoverage.echoListBool');
  @override
  Future<List<TcPoint>> echoPointList(List<TcPoint> values) =>
      throw UnimplementedError('NitroTypeCoverage.echoPointList');
  @override
  void submitCoalesced(int callId, int value, int dartPort) =>
      throw UnimplementedError('NitroTypeCoverage.submitCoalesced');
  @override
  Future<int> nativeAsyncInt(int value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncInt');
  @override
  Future<double> nativeAsyncDouble(double value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncDouble');
  @override
  Future<bool> nativeAsyncBool(bool value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncBool');
  @override
  Future<String> nativeAsyncString(String value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncString');
  @override
  Future<int?> nativeAsyncNullableInt(int? value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncNullableInt');
  @override
  Future<double?> nativeAsyncNullableDouble(double? value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncNullableDouble');
  @override
  Future<bool?> nativeAsyncNullableBool(bool? value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncNullableBool');
  @override
  Future<TcStatus> nativeAsyncStatus(TcStatus value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncStatus');
  @override
  Future<TcStatus?> nativeAsyncNullableStatus(TcStatus? value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncNullableStatus');
  @override
  Future<TcConfig> nativeAsyncConfig(TcConfig value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncConfig');
  @override
  Future<TcConfig> nativeAsyncPrintText(String text, {TcConfig? settings}) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncPrintText');
  @override
  String implVariant() =>
      throw UnimplementedError('NitroTypeCoverage.implVariant');
  @override
  Future<TcConfig?> nativeAsyncNullableConfig(TcConfig? value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncNullableConfig');
  @override
  Future<TcEvent> nativeAsyncEvent(TcEvent value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncEvent');
  @override
  Future<List<TcConfig>> nativeAsyncConfigList(List<TcConfig> values) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncConfigList');
  @override
  Future<List<TcStatus>> nativeAsyncStatusList(List<TcStatus> values) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncStatusList');
  @override
  Future<List<TcEvent>> nativeAsyncEventList(List<TcEvent> values) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncEventList');
  @override
  Future<List<int>> nativeAsyncIntList(List<int> values) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncIntList');
  @override
  Future<int> nativeAsyncWithCallback(int value, void Function(int) callback) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncWithCallback');
  @override
  Future<Map<String, int>> nativeAsyncCounts(int seed) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncCounts');
  @override
  Future<uint64?> nativeAsyncNullableUint64(uint64? value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncNullableUint64');
  @override
  Future<Map<String, int>> nativeAsyncEchoIntMap(Map<String, int> value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncEchoIntMap');
  @override
  Future<TcPoint> nativeAsyncEchoPoint(TcPoint value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncEchoPoint');
  @override
  Future<NitroAnyMap> nativeAsyncEchoAnyMap(NitroAnyMap value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncEchoAnyMap');
  @override
  void configureStringStream(List<String> values) =>
      throw UnimplementedError('NitroTypeCoverage.configureStringStream');
  @override
  void configureBatchStringStream(List<String> values) =>
      throw UnimplementedError('NitroTypeCoverage.configureBatchStringStream');
  @override
  void configureBlockIntStream(int from, int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureBlockIntStream');
  @override
  void onPointEvent(void Function(TcPoint) pointCb) =>
      throw UnimplementedError('NitroTypeCoverage.onPointEvent');
  @override
  void onDetailEvent(void Function(int, double) detailCb) =>
      throw UnimplementedError('NitroTypeCoverage.onDetailEvent');
  @override
  void onIntEvent(void Function(int) callback) =>
      throw UnimplementedError('NitroTypeCoverage.onIntEvent');
  @override
  void onBoolEvent(void Function(bool) boolCb) =>
      throw UnimplementedError('NitroTypeCoverage.onBoolEvent');
  @override
  void onDoubleEvent(void Function(double) doubleCb) =>
      throw UnimplementedError('NitroTypeCoverage.onDoubleEvent');
  @override
  void configureStream(int from, int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureStream');
  @override
  void configureDoubleStream(double start, int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureDoubleStream');
  @override
  void configureStatusStream(int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureStatusStream');
  @override
  void throwNative(String message) =>
      throw UnimplementedError('NitroTypeCoverage.throwNative');
  @override
  Future<void> throwNativeAsync(String message) =>
      throw UnimplementedError('NitroTypeCoverage.throwNativeAsync');
  @override
  Future<void> throwNativeNativeAsync(String message) =>
      throw UnimplementedError('NitroTypeCoverage.throwNativeNativeAsync');
  @override
  NitroResultValue<TcConfig> getConfigOrFail(bool shouldFail) =>
      throw UnimplementedError('NitroTypeCoverage.getConfigOrFail');
  @override
  Future<TcConfig?> nativeAsyncEchoOptionalConfig(TcConfig? config) =>
      throw UnimplementedError(
        'NitroTypeCoverage.nativeAsyncEchoOptionalConfig',
      );
  @override
  int addIntsFast(int a, int b) =>
      throw UnimplementedError('NitroTypeCoverage.addIntsFast');
  @override
  void touchFast() => throw UnimplementedError('NitroTypeCoverage.touchFast');
  @override
  Future<int> addIntsInline(int a, int b) =>
      throw UnimplementedError('NitroTypeCoverage.addIntsInline');
  @override
  FutureOr<int> addIntsInlineOr(int a, int b) =>
      throw UnimplementedError('NitroTypeCoverage.addIntsInlineOr');
  @override
  FutureOr<int> asyncIntOr(int value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncIntOr');
  @override
  FutureOr<String> nativeAsyncStringOr(String value) =>
      throw UnimplementedError('NitroTypeCoverage.nativeAsyncStringOr');
  @override
  double scaleFast(double v, double factor) =>
      throw UnimplementedError('NitroTypeCoverage.scaleFast');
  @override
  bool notFast(bool v) => throw UnimplementedError('NitroTypeCoverage.notFast');
  @override
  TcStatus nextStatusFast(TcStatus s) =>
      throw UnimplementedError('NitroTypeCoverage.nextStatusFast');
  @override
  int? optIncFast(int? v) =>
      throw UnimplementedError('NitroTypeCoverage.optIncFast');
  @override
  int strLenFast(String s) =>
      throw UnimplementedError('NitroTypeCoverage.strLenFast');
  @override
  int throwsFast(int v) =>
      throw UnimplementedError('NitroTypeCoverage.throwsFast');
  @override
  int bufferFill(NativeHandle<Void> buffer, int size, int byte) =>
      throw UnimplementedError('NitroTypeCoverage.bufferFill');
  @override
  int bufferFirstByteFast(NativeHandle<Void> buffer) =>
      throw UnimplementedError('NitroTypeCoverage.bufferFirstByteFast');
  @override
  int addIntsHot(int a, int b) =>
      throw UnimplementedError('NitroTypeCoverage.addIntsHot');
  @override
  int bufferFirstByteHot(NativeHandle<Void> buffer) =>
      throw UnimplementedError('NitroTypeCoverage.bufferFirstByteHot');
  @override
  NativeHandle<Void> acquireBuffer(int size) =>
      throw UnimplementedError('NitroTypeCoverage.acquireBuffer');
  @override
  TcEvent echoEvent(TcEvent event) =>
      throw UnimplementedError('NitroTypeCoverage.echoEvent');
  @override
  NitroResultValue<double> safeDiv(double a, double b) =>
      throw UnimplementedError('NitroTypeCoverage.safeDiv');
  @override
  NitroResultValue<String> validateLabel(String label) =>
      throw UnimplementedError('NitroTypeCoverage.validateLabel');
  @override
  Future<int> slowAsync(int delayMs) =>
      throw UnimplementedError('NitroTypeCoverage.slowAsync');
  @override
  TcDeepRecord echoDeepRecord(TcDeepRecord value) =>
      throw UnimplementedError('NitroTypeCoverage.echoDeepRecord');
  @override
  Future<TcDeepRecord> asyncDeepRecord(TcDeepRecord value) =>
      throw UnimplementedError('NitroTypeCoverage.asyncDeepRecord');
  @override
  Future<NativeHandle<Void>> asyncAcquireBuffer(int size) =>
      throw UnimplementedError('NitroTypeCoverage.asyncAcquireBuffer');
  @override
  Future<TcEvent> asyncEchoEvent(TcEvent event) =>
      throw UnimplementedError('NitroTypeCoverage.asyncEchoEvent');
  @override
  Future<NitroResultValue<double>> asyncSafeDiv(double a, double b) =>
      throw UnimplementedError('NitroTypeCoverage.asyncSafeDiv');
  @override
  Future<NitroResultValue<String>> asyncValidateLabel(String label) =>
      throw UnimplementedError('NitroTypeCoverage.asyncValidateLabel');
  @override
  TcPriority echoPriority(TcPriority value) =>
      throw UnimplementedError('NitroTypeCoverage.echoPriority');
  @override
  void configureBufferDropIntStream(int from, int count) =>
      throw UnimplementedError(
        'NitroTypeCoverage.configureBufferDropIntStream',
      );
  @override
  void onEventCallback(void Function(TcEvent) handler) =>
      throw UnimplementedError('NitroTypeCoverage.onEventCallback');
  @override
  void configureEventStream(int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureEventStream');
  @override
  List<TcStatus> getStatusList() =>
      throw UnimplementedError('NitroTypeCoverage.getStatusList');
  @override
  List<TcStatus> echoStatusList(List<TcStatus> values) =>
      throw UnimplementedError('NitroTypeCoverage.echoStatusList');
  @override
  List<TcEvent> getEventList() =>
      throw UnimplementedError('NitroTypeCoverage.getEventList');
  @override
  List<TcEvent> echoEventList(List<TcEvent> values) =>
      throw UnimplementedError('NitroTypeCoverage.echoEventList');
  @override
  void configureNullableStatusStream(int count) => throw UnimplementedError(
    'NitroTypeCoverage.configureNullableStatusStream',
  );
  @override
  void configureNullableStringStream(int count) => throw UnimplementedError(
    'NitroTypeCoverage.configureNullableStringStream',
  );
  @override
  TcPair echoPair(TcPair value) =>
      throw UnimplementedError('NitroTypeCoverage.echoPair');
  @override
  TcPair? echoNullablePair(TcPair? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullablePair');
  @override
  uint64 echoUint64(uint64 value) =>
      throw UnimplementedError('NitroTypeCoverage.echoUint64');
  @override
  uint64? echoNullableUint64(uint64? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableUint64');
  @override
  void configureUint64Stream(int from, int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureUint64Stream');
  @override
  void configureNullableUint64Stream(int count) => throw UnimplementedError(
    'NitroTypeCoverage.configureNullableUint64Stream',
  );
  @override
  int echoInt8(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt8');
  @override
  int echoInt16(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt16');
  @override
  int echoInt32(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoInt32');
  @override
  int echoUint8(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoUint8');
  @override
  int echoUint16(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoUint16');
  @override
  int echoUint32(int value) =>
      throw UnimplementedError('NitroTypeCoverage.echoUint32');
  @override
  double echoFloat(double value) =>
      throw UnimplementedError('NitroTypeCoverage.echoFloat');
  @override
  int? echoNullableInt32(int? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableInt32');
  @override
  double? echoNullableFloat(double? value) =>
      throw UnimplementedError('NitroTypeCoverage.echoNullableFloat');
  @override
  void configureNullableIntStream(int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureNullableIntStream');
  @override
  void configureNullableDoubleStream(int count) => throw UnimplementedError(
    'NitroTypeCoverage.configureNullableDoubleStream',
  );
  @override
  void configureNullableBoolStream(int count) =>
      throw UnimplementedError('NitroTypeCoverage.configureNullableBoolStream');
  @override
  int get precision => throw UnimplementedError('NitroTypeCoverage.precision');
  @override
  set precision(int value) =>
      throw UnimplementedError('NitroTypeCoverage.precision');
  @override
  String get tag => throw UnimplementedError('NitroTypeCoverage.tag');
  @override
  set tag(String value) => throw UnimplementedError('NitroTypeCoverage.tag');
  @override
  double? get nullableRate =>
      throw UnimplementedError('NitroTypeCoverage.nullableRate');
  @override
  set nullableRate(double? value) =>
      throw UnimplementedError('NitroTypeCoverage.nullableRate');
  @override
  bool get enabled => throw UnimplementedError('NitroTypeCoverage.enabled');
  @override
  set enabled(bool value) =>
      throw UnimplementedError('NitroTypeCoverage.enabled');
  @override
  TcStatus get currentStatus =>
      throw UnimplementedError('NitroTypeCoverage.currentStatus');
  @override
  set currentStatus(TcStatus value) =>
      throw UnimplementedError('NitroTypeCoverage.currentStatus');
  @override
  int? get nullableCounter =>
      throw UnimplementedError('NitroTypeCoverage.nullableCounter');
  @override
  set nullableCounter(int? value) =>
      throw UnimplementedError('NitroTypeCoverage.nullableCounter');
  @override
  bool? get optionalFlag =>
      throw UnimplementedError('NitroTypeCoverage.optionalFlag');
  @override
  set optionalFlag(bool? value) =>
      throw UnimplementedError('NitroTypeCoverage.optionalFlag');
  @override
  TcEvent get currentEvent =>
      throw UnimplementedError('NitroTypeCoverage.currentEvent');
  @override
  set currentEvent(TcEvent value) =>
      throw UnimplementedError('NitroTypeCoverage.currentEvent');
  @override
  Stream<TcConfig> configStream() =>
      throw UnimplementedError('NitroTypeCoverage.configStream');
  @override
  Stream<int> batchIntStream() =>
      throw UnimplementedError('NitroTypeCoverage.batchIntStream');
  @override
  Stream<double> batchDoubleStream() =>
      throw UnimplementedError('NitroTypeCoverage.batchDoubleStream');
  @override
  Stream<bool> batchBoolStream() =>
      throw UnimplementedError('NitroTypeCoverage.batchBoolStream');
  @override
  Stream<String> stringStream() =>
      throw UnimplementedError('NitroTypeCoverage.stringStream');
  @override
  Stream<String> batchStringStream() =>
      throw UnimplementedError('NitroTypeCoverage.batchStringStream');
  @override
  Stream<int> blockIntStream() =>
      throw UnimplementedError('NitroTypeCoverage.blockIntStream');
  @override
  Stream<int> intStream() =>
      throw UnimplementedError('NitroTypeCoverage.intStream');
  @override
  Stream<TcPoint> pointStream() =>
      throw UnimplementedError('NitroTypeCoverage.pointStream');
  @override
  Stream<bool> boolStream() =>
      throw UnimplementedError('NitroTypeCoverage.boolStream');
  @override
  Stream<double> doubleStream() =>
      throw UnimplementedError('NitroTypeCoverage.doubleStream');
  @override
  Stream<TcStatus> statusStream() =>
      throw UnimplementedError('NitroTypeCoverage.statusStream');
  @override
  Stream<int> bufferDropIntStream() =>
      throw UnimplementedError('NitroTypeCoverage.bufferDropIntStream');
  @override
  Stream<TcEvent> eventStream() =>
      throw UnimplementedError('NitroTypeCoverage.eventStream');
  @override
  Stream<TcStatus?> nullableStatusStream() =>
      throw UnimplementedError('NitroTypeCoverage.nullableStatusStream');
  @override
  Stream<String?> nullableStringStream() =>
      throw UnimplementedError('NitroTypeCoverage.nullableStringStream');
  @override
  Stream<uint64> uint64Stream() =>
      throw UnimplementedError('NitroTypeCoverage.uint64Stream');
  @override
  Stream<uint64?> nullableUint64Stream() =>
      throw UnimplementedError('NitroTypeCoverage.nullableUint64Stream');
  @override
  Stream<int?> nullableIntStream() =>
      throw UnimplementedError('NitroTypeCoverage.nullableIntStream');
  @override
  Stream<double?> nullableDoubleStream() =>
      throw UnimplementedError('NitroTypeCoverage.nullableDoubleStream');
  @override
  Stream<bool?> nullableBoolStream() =>
      throw UnimplementedError('NitroTypeCoverage.nullableBoolStream');
}
