// HybridNitroTypeCoverage — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
//
// NOT part of the active build: windows/CMakeLists.txt does
// `add_subdirectory(../src)`, which compiles the SHARED
// ../src/HybridNitroTypeCoverage.cpp for both Windows and Linux (see
// src/CMakeLists.txt's `if(NOT ANDROID)` target_sources call) — that file
// has the real implementation. This one is orphaned generator scaffolding
// left over from a per-platform Windows layout; it is never added to any
// CMake target, so leaving it as a stub does not block the build.
#include "../../lib/src/generated/cpp/nitro_type_coverage.native.g.h"

#include <string>

class HybridNitroTypeCoverageImpl final : public HybridNitroTypeCoverage {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroTypeCoverage
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_type_coverage_register_impl(new HybridNitroTypeCoverageImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
