// HybridNitroTypeCoverage — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_type_coverage.native.g.h"

#include <string>

class HybridNitroTypeCoverageImpl final : public HybridNitroTypeCoverage {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroTypeCoverage
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_type_coverage_register_impl(new HybridNitroTypeCoverageImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
