// Generated by nitrogen link — do not edit.
// Compiled as C (not C++) so the void*/function-pointer casts
// in dart_api_dl.c are accepted by the compiler.
#include "/Users/shreemanarjunsahu/personal/flutter_package/nitro_ecosystem/packages/nitro/src/native/dart_api_dl.c"
